/*******************************************************************************
*                          AUTOGENERATED BY REGBLOCK                           *
*                            Do not edit manually.                             *
*          Edit the source file (or regblock utility) and regenerate.          *
*******************************************************************************/

// Block name           : dma
// Bus type             : apb
// Bus data width       : 32
// Bus address width    : 16

module dma_regs (
	input wire clk,
	input wire rst_n,
	
	// APB Port
	input wire apbs_psel,
	input wire apbs_penable,
	input wire apbs_pwrite,
	input wire [15:0] apbs_paddr,
	input wire [31:0] apbs_pwdata,
	output wire [31:0] apbs_prdata,
	output wire apbs_pready,
	output wire apbs_pslverr,
	
	// Register interfaces
	output reg  ctrl_count_mode_o,
	output reg  ctrl_half_irq_o,
	output reg  ctrl_over_irq_o,
	output reg  ctrl_daddrinc_o,
	output reg  ctrl_saddrinc_o,
	output reg [2:0] ctrl_dwidth_o,
	input wire  ctrl_start_i,
	output reg  ctrl_start_o,
	output reg ctrl_start_wen,
	output reg ctrl_start_ren,
	output reg [31:0] sdaddr_o,
	output reg [31:0] ssaddr_o,
	output reg [5:0] srbit_o,
	output reg  srpol_o,
	output reg [31:0] ddaddr_o,
	output reg [31:0] dsaddr_o,
	output reg [5:0] drbit_o,
	output reg  drpol_o,
	output reg [31:0] count_o,
	input wire  irq_pend_halfover_pend_i,
	output reg  irq_pend_halfover_pend_o,
	input wire  irq_pend_over_pend_i,
	output reg  irq_pend_over_pend_o
);

// APB adapter
wire [31:0] wdata = apbs_pwdata;
reg [31:0] rdata;
wire wen = apbs_psel && apbs_penable && apbs_pwrite;
wire ren = apbs_psel && apbs_penable && !apbs_pwrite;
wire [15:0] addr = apbs_paddr & 16'h3c;
assign apbs_prdata = rdata;
assign apbs_pready = 1'b1;
assign apbs_pslverr = 1'b0;

localparam ADDR_CTRL = 0;
localparam ADDR_SDADDR = 4;
localparam ADDR_SSADDR = 8;
localparam ADDR_SRBIT = 12;
localparam ADDR_SRPOL = 16;
localparam ADDR_DDADDR = 20;
localparam ADDR_DSADDR = 24;
localparam ADDR_DRBIT = 28;
localparam ADDR_DRPOL = 32;
localparam ADDR_COUNT = 36;
localparam ADDR_IRQ_PEND = 40;

wire __ctrl_wen = wen && addr == ADDR_CTRL;
wire __ctrl_ren = ren && addr == ADDR_CTRL;
wire __sdaddr_wen = wen && addr == ADDR_SDADDR;
wire __sdaddr_ren = ren && addr == ADDR_SDADDR;
wire __ssaddr_wen = wen && addr == ADDR_SSADDR;
wire __ssaddr_ren = ren && addr == ADDR_SSADDR;
wire __srbit_wen = wen && addr == ADDR_SRBIT;
wire __srbit_ren = ren && addr == ADDR_SRBIT;
wire __srpol_wen = wen && addr == ADDR_SRPOL;
wire __srpol_ren = ren && addr == ADDR_SRPOL;
wire __ddaddr_wen = wen && addr == ADDR_DDADDR;
wire __ddaddr_ren = ren && addr == ADDR_DDADDR;
wire __dsaddr_wen = wen && addr == ADDR_DSADDR;
wire __dsaddr_ren = ren && addr == ADDR_DSADDR;
wire __drbit_wen = wen && addr == ADDR_DRBIT;
wire __drbit_ren = ren && addr == ADDR_DRBIT;
wire __drpol_wen = wen && addr == ADDR_DRPOL;
wire __drpol_ren = ren && addr == ADDR_DRPOL;
wire __count_wen = wen && addr == ADDR_COUNT;
wire __count_ren = ren && addr == ADDR_COUNT;
wire __irq_pend_wen = wen && addr == ADDR_IRQ_PEND;
wire __irq_pend_ren = ren && addr == ADDR_IRQ_PEND;

wire  ctrl_count_mode_wdata = wdata[8];
wire  ctrl_count_mode_rdata;
wire  ctrl_half_irq_wdata = wdata[7];
wire  ctrl_half_irq_rdata;
wire  ctrl_over_irq_wdata = wdata[6];
wire  ctrl_over_irq_rdata;
wire  ctrl_daddrinc_wdata = wdata[5];
wire  ctrl_daddrinc_rdata;
wire  ctrl_saddrinc_wdata = wdata[4];
wire  ctrl_saddrinc_rdata;
wire [2:0] ctrl_dwidth_wdata = wdata[3:1];
wire [2:0] ctrl_dwidth_rdata;
wire  ctrl_start_wdata = wdata[0];
wire  ctrl_start_rdata;
wire [31:0] __ctrl_rdata = {23'h0, ctrl_count_mode_rdata, ctrl_half_irq_rdata, ctrl_over_irq_rdata, ctrl_daddrinc_rdata, ctrl_saddrinc_rdata, ctrl_dwidth_rdata, ctrl_start_rdata};
assign ctrl_count_mode_rdata = ctrl_count_mode_o;
assign ctrl_half_irq_rdata = ctrl_half_irq_o;
assign ctrl_over_irq_rdata = ctrl_over_irq_o;
assign ctrl_daddrinc_rdata = ctrl_daddrinc_o;
assign ctrl_saddrinc_rdata = ctrl_saddrinc_o;
assign ctrl_dwidth_rdata = ctrl_dwidth_o;
assign ctrl_start_rdata = ctrl_start_i;

wire [31:0] sdaddr_wdata = wdata[31:0];
wire [31:0] sdaddr_rdata;
wire [31:0] __sdaddr_rdata = {sdaddr_rdata};
assign sdaddr_rdata = sdaddr_o;

wire [31:0] ssaddr_wdata = wdata[31:0];
wire [31:0] ssaddr_rdata;
wire [31:0] __ssaddr_rdata = {ssaddr_rdata};
assign ssaddr_rdata = ssaddr_o;

wire [5:0] srbit_wdata = wdata[5:0];
wire [5:0] srbit_rdata;
wire [31:0] __srbit_rdata = {26'h0, srbit_rdata};
assign srbit_rdata = srbit_o;

wire  srpol_wdata = wdata[0];
wire  srpol_rdata;
wire [31:0] __srpol_rdata = {31'h0, srpol_rdata};
assign srpol_rdata = srpol_o;

wire [31:0] ddaddr_wdata = wdata[31:0];
wire [31:0] ddaddr_rdata;
wire [31:0] __ddaddr_rdata = {ddaddr_rdata};
assign ddaddr_rdata = ddaddr_o;

wire [31:0] dsaddr_wdata = wdata[31:0];
wire [31:0] dsaddr_rdata;
wire [31:0] __dsaddr_rdata = {dsaddr_rdata};
assign dsaddr_rdata = dsaddr_o;

wire [5:0] drbit_wdata = wdata[5:0];
wire [5:0] drbit_rdata;
wire [31:0] __drbit_rdata = {26'h0, drbit_rdata};
assign drbit_rdata = drbit_o;

wire  drpol_wdata = wdata[0];
wire  drpol_rdata;
wire [31:0] __drpol_rdata = {31'h0, drpol_rdata};
assign drpol_rdata = drpol_o;

wire [31:0] count_wdata = wdata[31:0];
wire [31:0] count_rdata;
wire [31:0] __count_rdata = {count_rdata};
assign count_rdata = count_o;

wire  irq_pend_halfover_pend_wdata = wdata[1];
wire  irq_pend_halfover_pend_rdata;
wire  irq_pend_over_pend_wdata = wdata[0];
wire  irq_pend_over_pend_rdata;
wire [31:0] __irq_pend_rdata = {30'h0, irq_pend_halfover_pend_rdata, irq_pend_over_pend_rdata};
reg  irq_pend_halfover_pend;
assign irq_pend_halfover_pend_rdata = irq_pend_halfover_pend;
reg  irq_pend_over_pend;
assign irq_pend_over_pend_rdata = irq_pend_over_pend;

always @ (*) begin
	case (addr)
		ADDR_CTRL: rdata = __ctrl_rdata;
		ADDR_SDADDR: rdata = __sdaddr_rdata;
		ADDR_SSADDR: rdata = __ssaddr_rdata;
		ADDR_SRBIT: rdata = __srbit_rdata;
		ADDR_SRPOL: rdata = __srpol_rdata;
		ADDR_DDADDR: rdata = __ddaddr_rdata;
		ADDR_DSADDR: rdata = __dsaddr_rdata;
		ADDR_DRBIT: rdata = __drbit_rdata;
		ADDR_DRPOL: rdata = __drpol_rdata;
		ADDR_COUNT: rdata = __count_rdata;
		ADDR_IRQ_PEND: rdata = __irq_pend_rdata;
		default: rdata = 32'h0;
	endcase
	ctrl_start_wen = __ctrl_wen;
	ctrl_start_o = ctrl_start_wdata;
	ctrl_start_ren = __ctrl_ren;
	irq_pend_halfover_pend_o = irq_pend_halfover_pend;
	irq_pend_over_pend_o = irq_pend_over_pend;
end

always @ (posedge clk or negedge rst_n) begin
	if (!rst_n) begin
		ctrl_count_mode_o <= 1'h0;
		ctrl_half_irq_o <= 1'h0;
		ctrl_over_irq_o <= 1'h0;
		ctrl_daddrinc_o <= 1'h0;
		ctrl_saddrinc_o <= 1'h0;
		ctrl_dwidth_o <= 3'h0;
		sdaddr_o <= 32'h0;
		ssaddr_o <= 32'h0;
		srbit_o <= 6'h0;
		srpol_o <= 1'h0;
		ddaddr_o <= 32'h0;
		dsaddr_o <= 32'h0;
		drbit_o <= 6'h0;
		drpol_o <= 1'h0;
		count_o <= 32'h0;
		irq_pend_halfover_pend <= 1'h0;
		irq_pend_over_pend <= 1'h0;
	end else begin
		if (__ctrl_wen)
			ctrl_count_mode_o <= ctrl_count_mode_wdata;
		if (__ctrl_wen)
			ctrl_half_irq_o <= ctrl_half_irq_wdata;
		if (__ctrl_wen)
			ctrl_over_irq_o <= ctrl_over_irq_wdata;
		if (__ctrl_wen)
			ctrl_daddrinc_o <= ctrl_daddrinc_wdata;
		if (__ctrl_wen)
			ctrl_saddrinc_o <= ctrl_saddrinc_wdata;
		if (__ctrl_wen)
			ctrl_dwidth_o <= ctrl_dwidth_wdata;
		if (__sdaddr_wen)
			sdaddr_o <= sdaddr_wdata;
		if (__ssaddr_wen)
			ssaddr_o <= ssaddr_wdata;
		if (__srbit_wen)
			srbit_o <= srbit_wdata;
		if (__srpol_wen)
			srpol_o <= srpol_wdata;
		if (__ddaddr_wen)
			ddaddr_o <= ddaddr_wdata;
		if (__dsaddr_wen)
			dsaddr_o <= dsaddr_wdata;
		if (__drbit_wen)
			drbit_o <= drbit_wdata;
		if (__drpol_wen)
			drpol_o <= drpol_wdata;
		if (__count_wen)
			count_o <= count_wdata;
		irq_pend_halfover_pend <= (irq_pend_halfover_pend && !(__irq_pend_wen && irq_pend_halfover_pend_wdata)) || irq_pend_halfover_pend_i;
		irq_pend_over_pend <= (irq_pend_over_pend && !(__irq_pend_wen && irq_pend_over_pend_wdata)) || irq_pend_over_pend_i;
	end
end

endmodule
