/*******************************************************************************
*                          AUTOGENERATED BY REGBLOCK                           *
*                            Do not edit manually.                             *
*          Edit the source file (or regblock utility) and regenerate.          *
*******************************************************************************/

#ifndef _DMA_REGS_H_
#define _DMA_REGS_H_

// Block name           : dma
// Bus type             : apb
// Bus data width       : 32
// Bus address width    : 16

#define DMA_CTRL_OFFS 0
#define DMA_SDADDR_OFFS 4
#define DMA_SSADDR_OFFS 8
#define DMA_SRBIT_OFFS 12
#define DMA_SRPOL_OFFS 16
#define DMA_DDADDR_OFFS 20
#define DMA_DSADDR_OFFS 24
#define DMA_DRBIT_OFFS 28
#define DMA_DRPOL_OFFS 32
#define DMA_COUNT_OFFS 36
#define DMA_IRQ_PEND_OFFS 40

/*******************************************************************************
*                                     CTRL                                     *
*******************************************************************************/

// Control register

// Field: CTRL_COUNT_MODE  Access: RW
// If 0, oneshot mode; 1, circle mode
#define DMA_CTRL_COUNT_MODE_LSB  8
#define DMA_CTRL_COUNT_MODE_BITS 1
#define DMA_CTRL_COUNT_MODE_MASK 0x100
// Field: CTRL_HALF_IRQ  Access: RW
// If 1, gen irq when transform half over
#define DMA_CTRL_HALF_IRQ_LSB  7
#define DMA_CTRL_HALF_IRQ_BITS 1
#define DMA_CTRL_HALF_IRQ_MASK 0x80
// Field: CTRL_OVER_IRQ  Access: RW
// If 1, gen irq when transform over
#define DMA_CTRL_OVER_IRQ_LSB  6
#define DMA_CTRL_OVER_IRQ_BITS 1
#define DMA_CTRL_OVER_IRQ_MASK 0x40
// Field: CTRL_DADDRINC  Access: RW
// If 1, auto increase the dest addr by dwidth
#define DMA_CTRL_DADDRINC_LSB  5
#define DMA_CTRL_DADDRINC_BITS 1
#define DMA_CTRL_DADDRINC_MASK 0x20
// Field: CTRL_SADDRINC  Access: RW
// If 1, auto increase the src addr by dwidth
#define DMA_CTRL_SADDRINC_LSB  4
#define DMA_CTRL_SADDRINC_BITS 1
#define DMA_CTRL_SADDRINC_MASK 0x10
// Field: CTRL_DWIDTH  Access: RW
// the transform data width, 0: 8, 1: 16, 2: 32
#define DMA_CTRL_DWIDTH_LSB  1
#define DMA_CTRL_DWIDTH_BITS 3
#define DMA_CTRL_DWIDTH_MASK 0xe
// Field: CTRL_START  Access: RWF
// write 1 to start the dma
#define DMA_CTRL_START_LSB  0
#define DMA_CTRL_START_BITS 1
#define DMA_CTRL_START_MASK 0x1

/*******************************************************************************
*                                    SDADDR                                    *
*******************************************************************************/

// Source data address register

// Field: SDADDR  Access: RW
// source data address.
#define DMA_SDADDR_LSB  0
#define DMA_SDADDR_BITS 32
#define DMA_SDADDR_MASK 0xffffffff

/*******************************************************************************
*                                    SSADDR                                    *
*******************************************************************************/

// Source status address register

// Field: SSADDR  Access: RW
// source status address.
#define DMA_SSADDR_LSB  0
#define DMA_SSADDR_BITS 32
#define DMA_SSADDR_MASK 0xffffffff

/*******************************************************************************
*                                    SRBIT                                     *
*******************************************************************************/

// Source ready bit register

// Field: SRBIT  Access: RW
// source data ready bit, 32: always ready
#define DMA_SRBIT_LSB  0
#define DMA_SRBIT_BITS 6
#define DMA_SRBIT_MASK 0x3f

/*******************************************************************************
*                                    SRPOL                                     *
*******************************************************************************/

// Source ready bit polarity register

// Field: SRPOL  Access: RW
// source data ready polarity
#define DMA_SRPOL_LSB  0
#define DMA_SRPOL_BITS 1
#define DMA_SRPOL_MASK 0x1

/*******************************************************************************
*                                    DDADDR                                    *
*******************************************************************************/

// Destination data address register

// Field: DDADDR  Access: RW
// Destination data address.
#define DMA_DDADDR_LSB  0
#define DMA_DDADDR_BITS 32
#define DMA_DDADDR_MASK 0xffffffff

/*******************************************************************************
*                                    DSADDR                                    *
*******************************************************************************/

// Destination status address register

// Field: DSADDR  Access: RW
// Destination status address.
#define DMA_DSADDR_LSB  0
#define DMA_DSADDR_BITS 32
#define DMA_DSADDR_MASK 0xffffffff

/*******************************************************************************
*                                    DRBIT                                     *
*******************************************************************************/

// Destination ready bit register

// Field: DRBIT  Access: RW
// destination data ready bit, 32: always ready
#define DMA_DRBIT_LSB  0
#define DMA_DRBIT_BITS 6
#define DMA_DRBIT_MASK 0x3f

/*******************************************************************************
*                                    DRPOL                                     *
*******************************************************************************/

// Destination ready bit polarity register

// Field: DRPOL  Access: RW
// Destination data ready polarity
#define DMA_DRPOL_LSB  0
#define DMA_DRPOL_BITS 1
#define DMA_DRPOL_MASK 0x1

/*******************************************************************************
*                                    COUNT                                     *
*******************************************************************************/

// Data count register

// Field: COUNT  Access: RW
// How many data to be transformed, Unit: byte
#define DMA_COUNT_LSB  0
#define DMA_COUNT_BITS 32
#define DMA_COUNT_MASK 0xffffffff

/*******************************************************************************
*                                   IRQ_PEND                                   *
*******************************************************************************/

// Interrupt pending register

// Field: IRQ_PEND_HALFOVER_PEND  Access: W1C
// transform half over irq pending, write 1 to be clear
#define DMA_IRQ_PEND_HALFOVER_PEND_LSB  1
#define DMA_IRQ_PEND_HALFOVER_PEND_BITS 1
#define DMA_IRQ_PEND_HALFOVER_PEND_MASK 0x2
// Field: IRQ_PEND_OVER_PEND  Access: W1C
// transform over irq pending, write 1 to be clear
#define DMA_IRQ_PEND_OVER_PEND_LSB  0
#define DMA_IRQ_PEND_OVER_PEND_BITS 1
#define DMA_IRQ_PEND_OVER_PEND_MASK 0x1

#endif // _DMA_REGS_H_
