/*******************************************************************************
*                          AUTOGENERATED BY REGBLOCK                           *
*                            Do not edit manually.                             *
*          Edit the source file (or regblock utility) and regenerate.          *
*******************************************************************************/

#ifndef _PIO_REGS_H_
#define _PIO_REGS_H_

// Block name           : pio
// Bus type             : apb
// Bus data width       : 32
// Bus address width    : 16

#define PIO_CTRL_OFFS 0
#define PIO_IRQ_INTE_OFFS 4
#define PIO_IRQ_INTP_OFFS 8
#define PIO_PINS_DATA_OFFS 12
#define PIO_PINS_DIR_OFFS 16
#define PIO_PINS_DATA_SET_OFFS 20
#define PIO_PINS_DATA_CLR_OFFS 24
#define PIO_CLKDIV0_OFFS 28
#define PIO_PINCTRL0_OFFS 32
#define PIO_EXECCTRL0_OFFS 36
#define PIO_SHIFTCTRL0_OFFS 40
#define PIO_INSTR0_OFFS 44
#define PIO_PUSH0_OFFS 48
#define PIO_PULL0_OFFS 52
#define PIO_FSTAT0_OFFS 56
#define PIO_FCTRL0_OFFS 60
#define PIO_CLKDIV1_OFFS 64
#define PIO_PINCTRL1_OFFS 68
#define PIO_EXECCTRL1_OFFS 72
#define PIO_SHIFTCTRL1_OFFS 76
#define PIO_INSTR1_OFFS 80
#define PIO_PUSH1_OFFS 84
#define PIO_PULL1_OFFS 88
#define PIO_FSTAT1_OFFS 92
#define PIO_FCTRL1_OFFS 96
#define PIO_CLKDIV2_OFFS 100
#define PIO_PINCTRL2_OFFS 104
#define PIO_EXECCTRL2_OFFS 108
#define PIO_SHIFTCTRL2_OFFS 112
#define PIO_INSTR2_OFFS 116
#define PIO_PUSH2_OFFS 120
#define PIO_PULL2_OFFS 124
#define PIO_FSTAT2_OFFS 128
#define PIO_FCTRL2_OFFS 132
#define PIO_CLKDIV3_OFFS 136
#define PIO_PINCTRL3_OFFS 140
#define PIO_EXECCTRL3_OFFS 144
#define PIO_SHIFTCTRL3_OFFS 148
#define PIO_INSTR3_OFFS 152
#define PIO_PUSH3_OFFS 156
#define PIO_PULL3_OFFS 160
#define PIO_FSTAT3_OFFS 164
#define PIO_FCTRL3_OFFS 168
#define PIO_INSTRMEM0_OFFS 172
#define PIO_INSTRMEM1_OFFS 176
#define PIO_INSTRMEM2_OFFS 180
#define PIO_INSTRMEM3_OFFS 184
#define PIO_INSTRMEM4_OFFS 188
#define PIO_INSTRMEM5_OFFS 192
#define PIO_INSTRMEM6_OFFS 196
#define PIO_INSTRMEM7_OFFS 200
#define PIO_INSTRMEM8_OFFS 204
#define PIO_INSTRMEM9_OFFS 208
#define PIO_INSTRMEM10_OFFS 212
#define PIO_INSTRMEM11_OFFS 216
#define PIO_INSTRMEM12_OFFS 220
#define PIO_INSTRMEM13_OFFS 224
#define PIO_INSTRMEM14_OFFS 228
#define PIO_INSTRMEM15_OFFS 232
#define PIO_INSTRMEM16_OFFS 236
#define PIO_INSTRMEM17_OFFS 240
#define PIO_INSTRMEM18_OFFS 244
#define PIO_INSTRMEM19_OFFS 248
#define PIO_INSTRMEM20_OFFS 252
#define PIO_INSTRMEM21_OFFS 256
#define PIO_INSTRMEM22_OFFS 260
#define PIO_INSTRMEM23_OFFS 264
#define PIO_INSTRMEM24_OFFS 268
#define PIO_INSTRMEM25_OFFS 272
#define PIO_INSTRMEM26_OFFS 276
#define PIO_INSTRMEM27_OFFS 280
#define PIO_INSTRMEM28_OFFS 284
#define PIO_INSTRMEM29_OFFS 288
#define PIO_INSTRMEM30_OFFS 292
#define PIO_INSTRMEM31_OFFS 296

/*******************************************************************************
*                                     CTRL                                     *
*******************************************************************************/

// PIO control register

// Field: CTRL_CLKDIV_RESTART  Access: WF
// Restart a state machine’s clock divider.
#define PIO_CTRL_CLKDIV_RESTART_LSB  8
#define PIO_CTRL_CLKDIV_RESTART_BITS 4
#define PIO_CTRL_CLKDIV_RESTART_MASK 0xf00
// Field: CTRL_SM_RESTART  Access: WF
// Write 1 to restart state machine.
#define PIO_CTRL_SM_RESTART_LSB  4
#define PIO_CTRL_SM_RESTART_BITS 4
#define PIO_CTRL_SM_RESTART_MASK 0xf0
// Field: CTRL_SM_ENABLE  Access: RW
// Enable/disable each of the four state machines by writing 1/0 to each of
// these four bits.
#define PIO_CTRL_SM_ENABLE_LSB  0
#define PIO_CTRL_SM_ENABLE_BITS 4
#define PIO_CTRL_SM_ENABLE_MASK 0xf

/*******************************************************************************
*                                   IRQ_INTE                                   *
*******************************************************************************/

// PIO interrupt enable register

// Field: IRQ_INTE_SM3_TXEMPTY  Access: RW
// State machine 3 tx fifo empty IRQ enable.
#define PIO_IRQ_INTE_SM3_TXEMPTY_LSB  19
#define PIO_IRQ_INTE_SM3_TXEMPTY_BITS 1
#define PIO_IRQ_INTE_SM3_TXEMPTY_MASK 0x80000
// Field: IRQ_INTE_SM2_TXEMPTY  Access: RW
// State machine 2 tx fifo empty IRQ enable.
#define PIO_IRQ_INTE_SM2_TXEMPTY_LSB  18
#define PIO_IRQ_INTE_SM2_TXEMPTY_BITS 1
#define PIO_IRQ_INTE_SM2_TXEMPTY_MASK 0x40000
// Field: IRQ_INTE_SM1_TXEMPTY  Access: RW
// State machine 1 tx fifo empty IRQ enable.
#define PIO_IRQ_INTE_SM1_TXEMPTY_LSB  17
#define PIO_IRQ_INTE_SM1_TXEMPTY_BITS 1
#define PIO_IRQ_INTE_SM1_TXEMPTY_MASK 0x20000
// Field: IRQ_INTE_SM0_TXEMPTY  Access: RW
// State machine 0 tx fifo empty IRQ enable.
#define PIO_IRQ_INTE_SM0_TXEMPTY_LSB  16
#define PIO_IRQ_INTE_SM0_TXEMPTY_BITS 1
#define PIO_IRQ_INTE_SM0_TXEMPTY_MASK 0x10000
// Field: IRQ_INTE_SM3_TXNFULL  Access: RW
// State machine 3 tx fifo not full IRQ enable.
#define PIO_IRQ_INTE_SM3_TXNFULL_LSB  15
#define PIO_IRQ_INTE_SM3_TXNFULL_BITS 1
#define PIO_IRQ_INTE_SM3_TXNFULL_MASK 0x8000
// Field: IRQ_INTE_SM2_TXNFULL  Access: RW
// State machine 2 tx fifo not full IRQ enable.
#define PIO_IRQ_INTE_SM2_TXNFULL_LSB  14
#define PIO_IRQ_INTE_SM2_TXNFULL_BITS 1
#define PIO_IRQ_INTE_SM2_TXNFULL_MASK 0x4000
// Field: IRQ_INTE_SM1_TXNFULL  Access: RW
// State machine 1 tx fifo not full IRQ enable.
#define PIO_IRQ_INTE_SM1_TXNFULL_LSB  13
#define PIO_IRQ_INTE_SM1_TXNFULL_BITS 1
#define PIO_IRQ_INTE_SM1_TXNFULL_MASK 0x2000
// Field: IRQ_INTE_SM0_TXNFULL  Access: RW
// State machine 0 tx fifo not full IRQ enable.
#define PIO_IRQ_INTE_SM0_TXNFULL_LSB  12
#define PIO_IRQ_INTE_SM0_TXNFULL_BITS 1
#define PIO_IRQ_INTE_SM0_TXNFULL_MASK 0x1000
// Field: IRQ_INTE_SM3_RXNEMPTY  Access: RW
// State machine 3 rx fifo not empty IRQ enable.
#define PIO_IRQ_INTE_SM3_RXNEMPTY_LSB  11
#define PIO_IRQ_INTE_SM3_RXNEMPTY_BITS 1
#define PIO_IRQ_INTE_SM3_RXNEMPTY_MASK 0x800
// Field: IRQ_INTE_SM2_RXNEMPTY  Access: RW
// State machine 2 rx fifo not empty IRQ enable.
#define PIO_IRQ_INTE_SM2_RXNEMPTY_LSB  10
#define PIO_IRQ_INTE_SM2_RXNEMPTY_BITS 1
#define PIO_IRQ_INTE_SM2_RXNEMPTY_MASK 0x400
// Field: IRQ_INTE_SM1_RXNEMPTY  Access: RW
// State machine 1 rx fifo not empty IRQ enable.
#define PIO_IRQ_INTE_SM1_RXNEMPTY_LSB  9
#define PIO_IRQ_INTE_SM1_RXNEMPTY_BITS 1
#define PIO_IRQ_INTE_SM1_RXNEMPTY_MASK 0x200
// Field: IRQ_INTE_SM0_RXNEMPTY  Access: RW
// State machine 0 rx fifo not empty IRQ enable.
#define PIO_IRQ_INTE_SM0_RXNEMPTY_LSB  8
#define PIO_IRQ_INTE_SM0_RXNEMPTY_BITS 1
#define PIO_IRQ_INTE_SM0_RXNEMPTY_MASK 0x100
// Field: IRQ_INTE_SM_INT  Access: RW
// State machine interrupt enable.
#define PIO_IRQ_INTE_SM_INT_LSB  0
#define PIO_IRQ_INTE_SM_INT_BITS 8
#define PIO_IRQ_INTE_SM_INT_MASK 0xff

/*******************************************************************************
*                                   IRQ_INTP                                   *
*******************************************************************************/

// PIO interrupt pending register

// Field: IRQ_INTP_SM3_TXEMPTY  Access: W1C
// State machine 3 tx fifo empty IRQ pending.
#define PIO_IRQ_INTP_SM3_TXEMPTY_LSB  19
#define PIO_IRQ_INTP_SM3_TXEMPTY_BITS 1
#define PIO_IRQ_INTP_SM3_TXEMPTY_MASK 0x80000
// Field: IRQ_INTP_SM2_TXEMPTY  Access: W1C
// State machine 2 tx fifo empty IRQ pending.
#define PIO_IRQ_INTP_SM2_TXEMPTY_LSB  18
#define PIO_IRQ_INTP_SM2_TXEMPTY_BITS 1
#define PIO_IRQ_INTP_SM2_TXEMPTY_MASK 0x40000
// Field: IRQ_INTP_SM1_TXEMPTY  Access: W1C
// State machine 1 tx fifo empty IRQ pending.
#define PIO_IRQ_INTP_SM1_TXEMPTY_LSB  17
#define PIO_IRQ_INTP_SM1_TXEMPTY_BITS 1
#define PIO_IRQ_INTP_SM1_TXEMPTY_MASK 0x20000
// Field: IRQ_INTP_SM0_TXEMPTY  Access: W1C
// State machine 0 tx fifo empty IRQ pending.
#define PIO_IRQ_INTP_SM0_TXEMPTY_LSB  16
#define PIO_IRQ_INTP_SM0_TXEMPTY_BITS 1
#define PIO_IRQ_INTP_SM0_TXEMPTY_MASK 0x10000
// Field: IRQ_INTP_SM3_TXNFULL  Access: W1C
// State machine 3 tx fifo not full IRQ pending.
#define PIO_IRQ_INTP_SM3_TXNFULL_LSB  15
#define PIO_IRQ_INTP_SM3_TXNFULL_BITS 1
#define PIO_IRQ_INTP_SM3_TXNFULL_MASK 0x8000
// Field: IRQ_INTP_SM2_TXNFULL  Access: W1C
// State machine 2 tx fifo not full IRQ pending.
#define PIO_IRQ_INTP_SM2_TXNFULL_LSB  14
#define PIO_IRQ_INTP_SM2_TXNFULL_BITS 1
#define PIO_IRQ_INTP_SM2_TXNFULL_MASK 0x4000
// Field: IRQ_INTP_SM1_TXNFULL  Access: W1C
// State machine 1 tx fifo not full IRQ pending.
#define PIO_IRQ_INTP_SM1_TXNFULL_LSB  13
#define PIO_IRQ_INTP_SM1_TXNFULL_BITS 1
#define PIO_IRQ_INTP_SM1_TXNFULL_MASK 0x2000
// Field: IRQ_INTP_SM0_TXNFULL  Access: W1C
// State machine 0 tx fifo not full IRQ pending.
#define PIO_IRQ_INTP_SM0_TXNFULL_LSB  12
#define PIO_IRQ_INTP_SM0_TXNFULL_BITS 1
#define PIO_IRQ_INTP_SM0_TXNFULL_MASK 0x1000
// Field: IRQ_INTP_SM3_RXNEMPTY  Access: W1C
// State machine 3 rx fifo not empty IRQ pending.
#define PIO_IRQ_INTP_SM3_RXNEMPTY_LSB  11
#define PIO_IRQ_INTP_SM3_RXNEMPTY_BITS 1
#define PIO_IRQ_INTP_SM3_RXNEMPTY_MASK 0x800
// Field: IRQ_INTP_SM2_RXNEMPTY  Access: W1C
// State machine 2 rx fifo not empty IRQ pending.
#define PIO_IRQ_INTP_SM2_RXNEMPTY_LSB  10
#define PIO_IRQ_INTP_SM2_RXNEMPTY_BITS 1
#define PIO_IRQ_INTP_SM2_RXNEMPTY_MASK 0x400
// Field: IRQ_INTP_SM1_RXNEMPTY  Access: W1C
// State machine 1 rx fifo not empty IRQ pending.
#define PIO_IRQ_INTP_SM1_RXNEMPTY_LSB  9
#define PIO_IRQ_INTP_SM1_RXNEMPTY_BITS 1
#define PIO_IRQ_INTP_SM1_RXNEMPTY_MASK 0x200
// Field: IRQ_INTP_SM0_RXNEMPTY  Access: W1C
// State machine 0 rx fifo not empty IRQ pending.
#define PIO_IRQ_INTP_SM0_RXNEMPTY_LSB  8
#define PIO_IRQ_INTP_SM0_RXNEMPTY_BITS 1
#define PIO_IRQ_INTP_SM0_RXNEMPTY_MASK 0x100
// Field: IRQ_INTP_SM_INT  Access: RWF
// State machine interrupt pending.
#define PIO_IRQ_INTP_SM_INT_LSB  0
#define PIO_IRQ_INTP_SM_INT_BITS 8
#define PIO_IRQ_INTP_SM_INT_MASK 0xff

/*******************************************************************************
*                                  PINS_DATA                                   *
*******************************************************************************/

// GPIO input or output data register

// Field: PINS_DATA_DATA  Access: RWF
// GPIO input or output data.
#define PIO_PINS_DATA_DATA_LSB  0
#define PIO_PINS_DATA_DATA_BITS 32
#define PIO_PINS_DATA_DATA_MASK 0xffffffff

/*******************************************************************************
*                                   PINS_DIR                                   *
*******************************************************************************/

// GPIO direction control register

// Field: PINS_DIR_DATA  Access: RWF
// GPIO direction control, 1: output, 0: input.
#define PIO_PINS_DIR_DATA_LSB  0
#define PIO_PINS_DIR_DATA_BITS 32
#define PIO_PINS_DIR_DATA_MASK 0xffffffff

/*******************************************************************************
*                                PINS_DATA_SET                                 *
*******************************************************************************/

// GPIO output data set register

// Field: PINS_DATA_SET_DATA  Access: WF
// Write 1 set, write 0 no effect.
#define PIO_PINS_DATA_SET_DATA_LSB  0
#define PIO_PINS_DATA_SET_DATA_BITS 32
#define PIO_PINS_DATA_SET_DATA_MASK 0xffffffff

/*******************************************************************************
*                                PINS_DATA_CLR                                 *
*******************************************************************************/

// GPIO output data clear register

// Field: PINS_DATA_CLR_DATA  Access: WF
// Write 1 clear, write 0 no effect.
#define PIO_PINS_DATA_CLR_DATA_LSB  0
#define PIO_PINS_DATA_CLR_DATA_BITS 32
#define PIO_PINS_DATA_CLR_DATA_MASK 0xffffffff

/*******************************************************************************
*                                   CLKDIV0                                    *
*******************************************************************************/

// SM0 clock divider register

// Field: CLKDIV0_CLKDIV  Access: RW
// Clock divisor register for state machine 0.
#define PIO_CLKDIV0_CLKDIV_LSB  0
#define PIO_CLKDIV0_CLKDIV_BITS 32
#define PIO_CLKDIV0_CLKDIV_MASK 0xffffffff

/*******************************************************************************
*                                   PINCTRL0                                   *
*******************************************************************************/

// State machine 0 pin control register

// Field: PINCTRL0_OUT_BASE  Access: RW
// The lowest-numbered pin that will be affected by an OUT PINS, OUT PINDIRS or
// MOV PINS instruction.
#define PIO_PINCTRL0_OUT_BASE_LSB  0
#define PIO_PINCTRL0_OUT_BASE_BITS 5
#define PIO_PINCTRL0_OUT_BASE_MASK 0x1f
// Field: PINCTRL0_SET_BASE  Access: RW
// The lowest-numbered pin that will be affected by a SET PINS or SET PINDIRS
// instruction.
#define PIO_PINCTRL0_SET_BASE_LSB  5
#define PIO_PINCTRL0_SET_BASE_BITS 5
#define PIO_PINCTRL0_SET_BASE_MASK 0x3e0
// Field: PINCTRL0_SIDE_BASE  Access: RW
// The lowest-numbered pin that will be affected by a side-set operation.
#define PIO_PINCTRL0_SIDE_BASE_LSB  10
#define PIO_PINCTRL0_SIDE_BASE_BITS 5
#define PIO_PINCTRL0_SIDE_BASE_MASK 0x7c00
// Field: PINCTRL0_IN_BASE  Access: RW
// The pin which is mapped to the least-significant bit of a state machine’s IN
// data bus.
#define PIO_PINCTRL0_IN_BASE_LSB  15
#define PIO_PINCTRL0_IN_BASE_BITS 5
#define PIO_PINCTRL0_IN_BASE_MASK 0xf8000
// Field: PINCTRL0_OUT_COUNT  Access: RW
// The number of pins asserted by an OUT PINS, OUT PINDIRS or MOV PINS
// instruction.
#define PIO_PINCTRL0_OUT_COUNT_LSB  20
#define PIO_PINCTRL0_OUT_COUNT_BITS 6
#define PIO_PINCTRL0_OUT_COUNT_MASK 0x3f00000
// Field: PINCTRL0_SET_COUNT  Access: RW
// The number of pins asserted by a SET. In the range 0 to 5 inclusive.
#define PIO_PINCTRL0_SET_COUNT_LSB  26
#define PIO_PINCTRL0_SET_COUNT_BITS 3
#define PIO_PINCTRL0_SET_COUNT_MASK 0x1c000000
// Field: PINCTRL0_SIDE_COUNT  Access: RW
// The number of MSBs of the Delay/Side-set instruction field which are used for
// side-set.
#define PIO_PINCTRL0_SIDE_COUNT_LSB  29
#define PIO_PINCTRL0_SIDE_COUNT_BITS 3
#define PIO_PINCTRL0_SIDE_COUNT_MASK 0xe0000000

/*******************************************************************************
*                                  EXECCTRL0                                   *
*******************************************************************************/

// Execution/behavioural settings register

// Field: EXECCTRL0_EXEC_STALLED  Access: RW
// If 1, an instruction written to INSTR is stalled, and latched by the state
// machine.
#define PIO_EXECCTRL0_EXEC_STALLED_LSB  31
#define PIO_EXECCTRL0_EXEC_STALLED_BITS 1
#define PIO_EXECCTRL0_EXEC_STALLED_MASK 0x80000000
// Field: EXECCTRL0_SIDESET_EN  Access: RW
// If 1, the MSB of the Delay/Side-set instruction field is used as side-set
// enable, rather than a side-set data bit.
#define PIO_EXECCTRL0_SIDESET_EN_LSB  30
#define PIO_EXECCTRL0_SIDESET_EN_BITS 1
#define PIO_EXECCTRL0_SIDESET_EN_MASK 0x40000000
// Field: EXECCTRL0_SIDE_PINDIR  Access: RW
// If 1, side-set data is asserted to pin directions, instead of pin values.
#define PIO_EXECCTRL0_SIDE_PINDIR_LSB  29
#define PIO_EXECCTRL0_SIDE_PINDIR_BITS 1
#define PIO_EXECCTRL0_SIDE_PINDIR_MASK 0x20000000
// Field: EXECCTRL0_JMP_PIN  Access: RW
// The GPIO number to use as condition for JMP PIN. Unaffected by input mapping.
#define PIO_EXECCTRL0_JMP_PIN_LSB  24
#define PIO_EXECCTRL0_JMP_PIN_BITS 5
#define PIO_EXECCTRL0_JMP_PIN_MASK 0x1f000000
// Field: EXECCTRL0_OUT_EN_SEL  Access: RW
// Which data bit to use for inline OUT enable.
#define PIO_EXECCTRL0_OUT_EN_SEL_LSB  19
#define PIO_EXECCTRL0_OUT_EN_SEL_BITS 5
#define PIO_EXECCTRL0_OUT_EN_SEL_MASK 0xf80000
// Field: EXECCTRL0_INLINE_OUT_EN  Access: RW
// If 1, use a bit of OUT data as an auxiliary write enable When used in
// conjunction with OUT_STICKY, writes with an enable of 0 will deassert the
// latest pin write.
#define PIO_EXECCTRL0_INLINE_OUT_EN_LSB  18
#define PIO_EXECCTRL0_INLINE_OUT_EN_BITS 1
#define PIO_EXECCTRL0_INLINE_OUT_EN_MASK 0x40000
// Field: EXECCTRL0_OUT_STICKY  Access: RW
// Continuously assert the most recent OUT/SET to the pins.
#define PIO_EXECCTRL0_OUT_STICKY_LSB  17
#define PIO_EXECCTRL0_OUT_STICKY_BITS 1
#define PIO_EXECCTRL0_OUT_STICKY_MASK 0x20000
// Field: EXECCTRL0_WRAP_TOP  Access: RW
// After reaching this address, execution is wrapped to wrap_bottom.
#define PIO_EXECCTRL0_WRAP_TOP_LSB  12
#define PIO_EXECCTRL0_WRAP_TOP_BITS 5
#define PIO_EXECCTRL0_WRAP_TOP_MASK 0x1f000
// Field: EXECCTRL0_WRAP_BOTTOM  Access: RW
// After reaching wrap_top, execution is wrapped to this address.
#define PIO_EXECCTRL0_WRAP_BOTTOM_LSB  7
#define PIO_EXECCTRL0_WRAP_BOTTOM_BITS 5
#define PIO_EXECCTRL0_WRAP_BOTTOM_MASK 0xf80
// Field: EXECCTRL0_STATUS_SEL  Access: RW
// Comparison used for the MOV x, STATUS instruction.
#define PIO_EXECCTRL0_STATUS_SEL_LSB  4
#define PIO_EXECCTRL0_STATUS_SEL_BITS 1
#define PIO_EXECCTRL0_STATUS_SEL_MASK 0x10
// Field: EXECCTRL0_STATUS_N  Access: RW
// Comparison level for the MOV x, STATUS instruction.
#define PIO_EXECCTRL0_STATUS_N_LSB  0
#define PIO_EXECCTRL0_STATUS_N_BITS 4
#define PIO_EXECCTRL0_STATUS_N_MASK 0xf

/*******************************************************************************
*                                  SHIFTCTRL0                                  *
*******************************************************************************/

// Control behaviour of the input/output shift registers for state machine

// Field: SHIFTCTRL0_OSR_THRESHOLD  Access: RW
// Pull threshold. Number of bits shifted out of OSR before autopull, or
// conditional pull (PULL IFEMPTY), will take place.
#define PIO_SHIFTCTRL0_OSR_THRESHOLD_LSB  26
#define PIO_SHIFTCTRL0_OSR_THRESHOLD_BITS 6
#define PIO_SHIFTCTRL0_OSR_THRESHOLD_MASK 0xfc000000
// Field: SHIFTCTRL0_ISR_THRESHOLD  Access: RW
// Push threshold. Number of bits shifted into ISR before autopush, or
// conditional push (PUSH IFFULL), will take place.
#define PIO_SHIFTCTRL0_ISR_THRESHOLD_LSB  20
#define PIO_SHIFTCTRL0_ISR_THRESHOLD_BITS 6
#define PIO_SHIFTCTRL0_ISR_THRESHOLD_MASK 0x3f00000
// Field: SHIFTCTRL0_OUT_SHIFT_DIR  Access: RW
// 1 = shift out of output shift register to right. 0 = to left.
#define PIO_SHIFTCTRL0_OUT_SHIFT_DIR_LSB  19
#define PIO_SHIFTCTRL0_OUT_SHIFT_DIR_BITS 1
#define PIO_SHIFTCTRL0_OUT_SHIFT_DIR_MASK 0x80000
// Field: SHIFTCTRL0_IN_SHIFT_DIR  Access: RW
// 1 = shift input shift register to right (data enters from left). 0 = to left.
#define PIO_SHIFTCTRL0_IN_SHIFT_DIR_LSB  18
#define PIO_SHIFTCTRL0_IN_SHIFT_DIR_BITS 1
#define PIO_SHIFTCTRL0_IN_SHIFT_DIR_MASK 0x40000
// Field: SHIFTCTRL0_AUTO_PULL  Access: RW
// Pull automatically when the output shift register is emptied, i.e.
#define PIO_SHIFTCTRL0_AUTO_PULL_LSB  17
#define PIO_SHIFTCTRL0_AUTO_PULL_BITS 1
#define PIO_SHIFTCTRL0_AUTO_PULL_MASK 0x20000
// Field: SHIFTCTRL0_AUTO_PUSH  Access: RW
// Push automatically when the input shift register is filled, i.e.
#define PIO_SHIFTCTRL0_AUTO_PUSH_LSB  16
#define PIO_SHIFTCTRL0_AUTO_PUSH_BITS 1
#define PIO_SHIFTCTRL0_AUTO_PUSH_MASK 0x10000
// Field: SHIFTCTRL0_CLEAR_RXFIFO  Access: WF
// Write 1 to clear RX fifo.
#define PIO_SHIFTCTRL0_CLEAR_RXFIFO_LSB  15
#define PIO_SHIFTCTRL0_CLEAR_RXFIFO_BITS 1
#define PIO_SHIFTCTRL0_CLEAR_RXFIFO_MASK 0x8000
// Field: SHIFTCTRL0_CLEAR_TXFIFO  Access: WF
// Write 1 to clear TX fifo.
#define PIO_SHIFTCTRL0_CLEAR_TXFIFO_LSB  14
#define PIO_SHIFTCTRL0_CLEAR_TXFIFO_BITS 1
#define PIO_SHIFTCTRL0_CLEAR_TXFIFO_MASK 0x4000
// Field: SHIFTCTRL0_TXFIFO_SHADOW_MODE  Access: RW
// Use shadow mode in txfifo.
#define PIO_SHIFTCTRL0_TXFIFO_SHADOW_MODE_LSB  12
#define PIO_SHIFTCTRL0_TXFIFO_SHADOW_MODE_BITS 1
#define PIO_SHIFTCTRL0_TXFIFO_SHADOW_MODE_MASK 0x1000
// Field: SHIFTCTRL0_TXFIFO_SHADOW_UPDATE  Access: RWF
// Use shadow TX FIFO data to update worked TX FIFO data
#define PIO_SHIFTCTRL0_TXFIFO_SHADOW_UPDATE_LSB  11
#define PIO_SHIFTCTRL0_TXFIFO_SHADOW_UPDATE_BITS 1
#define PIO_SHIFTCTRL0_TXFIFO_SHADOW_UPDATE_MASK 0x800
// Field: SHIFTCTRL0_FJOIN_RX  Access: RW
// When 1, RX FIFO steals the TX FIFO’s storage, and becomes twice as deep.
#define PIO_SHIFTCTRL0_FJOIN_RX_LSB  1
#define PIO_SHIFTCTRL0_FJOIN_RX_BITS 1
#define PIO_SHIFTCTRL0_FJOIN_RX_MASK 0x2
// Field: SHIFTCTRL0_FJOIN_TX  Access: RW
// When 1, TX FIFO steals the RX FIFO’s storage, and becomes twice as deep.
#define PIO_SHIFTCTRL0_FJOIN_TX_LSB  0
#define PIO_SHIFTCTRL0_FJOIN_TX_BITS 1
#define PIO_SHIFTCTRL0_FJOIN_TX_MASK 0x1

/*******************************************************************************
*                                    INSTR0                                    *
*******************************************************************************/

// Immediate instruction register

// Field: INSTR0_INSTR  Access: WF
// Instruction to be exec.
#define PIO_INSTR0_INSTR_LSB  0
#define PIO_INSTR0_INSTR_BITS 16
#define PIO_INSTR0_INSTR_MASK 0xffff

/*******************************************************************************
*                                    PUSH0                                     *
*******************************************************************************/

// TX data FIFO for SM0

// Field: PUSH0  Access: WF
#define PIO_PUSH0_LSB  0
#define PIO_PUSH0_BITS 32
#define PIO_PUSH0_MASK 0xffffffff

/*******************************************************************************
*                                    PULL0                                     *
*******************************************************************************/

// RX data FIFO for SM0

// Field: PULL0  Access: RF
#define PIO_PULL0_LSB  0
#define PIO_PULL0_BITS 32
#define PIO_PULL0_MASK 0xffffffff

/*******************************************************************************
*                                    FSTAT0                                    *
*******************************************************************************/

// FIFO status register for SM0

// Field: FSTAT0_TXLEVEL  Access: ROV
#define PIO_FSTAT0_TXLEVEL_LSB  0
#define PIO_FSTAT0_TXLEVEL_BITS 4
#define PIO_FSTAT0_TXLEVEL_MASK 0xf
// Field: FSTAT0_TXFULL  Access: ROV
#define PIO_FSTAT0_TXFULL_LSB  4
#define PIO_FSTAT0_TXFULL_BITS 1
#define PIO_FSTAT0_TXFULL_MASK 0x10
// Field: FSTAT0_TXEMPTY  Access: ROV
#define PIO_FSTAT0_TXEMPTY_LSB  5
#define PIO_FSTAT0_TXEMPTY_BITS 1
#define PIO_FSTAT0_TXEMPTY_MASK 0x20
// Field: FSTAT0_RXLEVEL  Access: ROV
#define PIO_FSTAT0_RXLEVEL_LSB  6
#define PIO_FSTAT0_RXLEVEL_BITS 4
#define PIO_FSTAT0_RXLEVEL_MASK 0x3c0
// Field: FSTAT0_RXFULL  Access: ROV
#define PIO_FSTAT0_RXFULL_LSB  10
#define PIO_FSTAT0_RXFULL_BITS 1
#define PIO_FSTAT0_RXFULL_MASK 0x400
// Field: FSTAT0_RXEMPTY  Access: ROV
#define PIO_FSTAT0_RXEMPTY_LSB  11
#define PIO_FSTAT0_RXEMPTY_BITS 1
#define PIO_FSTAT0_RXEMPTY_MASK 0x800

/*******************************************************************************
*                                    FCTRL0                                    *
*******************************************************************************/

// FIFO control register for SM0

// Field: FCTRL0_TXFIFO_PUSH_INDEX  Access: RWF
// tx fifo push index
#define PIO_FCTRL0_TXFIFO_PUSH_INDEX_LSB  0
#define PIO_FCTRL0_TXFIFO_PUSH_INDEX_BITS 2
#define PIO_FCTRL0_TXFIFO_PUSH_INDEX_MASK 0x3
// Field: FCTRL0_TXFIFO_PULL_INDEX  Access: RWF
// tx fifo pull index
#define PIO_FCTRL0_TXFIFO_PULL_INDEX_LSB  2
#define PIO_FCTRL0_TXFIFO_PULL_INDEX_BITS 2
#define PIO_FCTRL0_TXFIFO_PULL_INDEX_MASK 0xc
// Field: FCTRL0_TXFIFO_READ_EN  Access: RW
// tx fifo read enable
#define PIO_FCTRL0_TXFIFO_READ_EN_LSB  4
#define PIO_FCTRL0_TXFIFO_READ_EN_BITS 1
#define PIO_FCTRL0_TXFIFO_READ_EN_MASK 0x10
// Field: FCTRL0_RXFIFO_PUSH_INDEX  Access: RWF
// rx fifo push index
#define PIO_FCTRL0_RXFIFO_PUSH_INDEX_LSB  5
#define PIO_FCTRL0_RXFIFO_PUSH_INDEX_BITS 2
#define PIO_FCTRL0_RXFIFO_PUSH_INDEX_MASK 0x60
// Field: FCTRL0_RXFIFO_PULL_INDEX  Access: RWF
// rx fifo pull index
#define PIO_FCTRL0_RXFIFO_PULL_INDEX_LSB  7
#define PIO_FCTRL0_RXFIFO_PULL_INDEX_BITS 2
#define PIO_FCTRL0_RXFIFO_PULL_INDEX_MASK 0x180
// Field: FCTRL0_RXFIFO_WRITE_EN  Access: RW
// rx fifo write enable
#define PIO_FCTRL0_RXFIFO_WRITE_EN_LSB  9
#define PIO_FCTRL0_RXFIFO_WRITE_EN_BITS 1
#define PIO_FCTRL0_RXFIFO_WRITE_EN_MASK 0x200
// Field: FCTRL0_TX_FIFO_DATA_COUNT  Access: RWF
// set how many data count in tx fifo
#define PIO_FCTRL0_TX_FIFO_DATA_COUNT_LSB  10
#define PIO_FCTRL0_TX_FIFO_DATA_COUNT_BITS 3
#define PIO_FCTRL0_TX_FIFO_DATA_COUNT_MASK 0x1c00
// Field: FCTRL0_RX_FIFO_DATA_COUNT  Access: RWF
// set how many data count in rx fifo
#define PIO_FCTRL0_RX_FIFO_DATA_COUNT_LSB  13
#define PIO_FCTRL0_RX_FIFO_DATA_COUNT_BITS 3
#define PIO_FCTRL0_RX_FIFO_DATA_COUNT_MASK 0xe000

/*******************************************************************************
*                                   CLKDIV1                                    *
*******************************************************************************/

// SM1 clock divider register

// Field: CLKDIV1_CLKDIV  Access: RW
// Clock divisor register for state machine 1.
#define PIO_CLKDIV1_CLKDIV_LSB  0
#define PIO_CLKDIV1_CLKDIV_BITS 32
#define PIO_CLKDIV1_CLKDIV_MASK 0xffffffff

/*******************************************************************************
*                                   PINCTRL1                                   *
*******************************************************************************/

// State machine 1 pin control register

// Field: PINCTRL1_OUT_BASE  Access: RW
// The lowest-numbered pin that will be affected by an OUT PINS, OUT PINDIRS or
// MOV PINS instruction.
#define PIO_PINCTRL1_OUT_BASE_LSB  0
#define PIO_PINCTRL1_OUT_BASE_BITS 5
#define PIO_PINCTRL1_OUT_BASE_MASK 0x1f
// Field: PINCTRL1_SET_BASE  Access: RW
// The lowest-numbered pin that will be affected by a SET PINS or SET PINDIRS
// instruction.
#define PIO_PINCTRL1_SET_BASE_LSB  5
#define PIO_PINCTRL1_SET_BASE_BITS 5
#define PIO_PINCTRL1_SET_BASE_MASK 0x3e0
// Field: PINCTRL1_SIDE_BASE  Access: RW
// The lowest-numbered pin that will be affected by a side-set operation.
#define PIO_PINCTRL1_SIDE_BASE_LSB  10
#define PIO_PINCTRL1_SIDE_BASE_BITS 5
#define PIO_PINCTRL1_SIDE_BASE_MASK 0x7c00
// Field: PINCTRL1_IN_BASE  Access: RW
// The pin which is mapped to the least-significant bit of a state machine’s IN
// data bus.
#define PIO_PINCTRL1_IN_BASE_LSB  15
#define PIO_PINCTRL1_IN_BASE_BITS 5
#define PIO_PINCTRL1_IN_BASE_MASK 0xf8000
// Field: PINCTRL1_OUT_COUNT  Access: RW
// The number of pins asserted by an OUT PINS, OUT PINDIRS or MOV PINS
// instruction.
#define PIO_PINCTRL1_OUT_COUNT_LSB  20
#define PIO_PINCTRL1_OUT_COUNT_BITS 6
#define PIO_PINCTRL1_OUT_COUNT_MASK 0x3f00000
// Field: PINCTRL1_SET_COUNT  Access: RW
// The number of pins asserted by a SET. In the range 0 to 5 inclusive.
#define PIO_PINCTRL1_SET_COUNT_LSB  26
#define PIO_PINCTRL1_SET_COUNT_BITS 3
#define PIO_PINCTRL1_SET_COUNT_MASK 0x1c000000
// Field: PINCTRL1_SIDE_COUNT  Access: RW
// The number of MSBs of the Delay/Side-set instruction field which are used for
// side-set.
#define PIO_PINCTRL1_SIDE_COUNT_LSB  29
#define PIO_PINCTRL1_SIDE_COUNT_BITS 3
#define PIO_PINCTRL1_SIDE_COUNT_MASK 0xe0000000

/*******************************************************************************
*                                  EXECCTRL1                                   *
*******************************************************************************/

// Execution/behavioural settings register

// Field: EXECCTRL1_EXEC_STALLED  Access: RW
// If 1, an instruction written to INSTR is stalled, and latched by the state
// machine.
#define PIO_EXECCTRL1_EXEC_STALLED_LSB  31
#define PIO_EXECCTRL1_EXEC_STALLED_BITS 1
#define PIO_EXECCTRL1_EXEC_STALLED_MASK 0x80000000
// Field: EXECCTRL1_SIDESET_EN  Access: RW
// If 1, the MSB of the Delay/Side-set instruction field is used as side-set
// enable, rather than a side-set data bit.
#define PIO_EXECCTRL1_SIDESET_EN_LSB  30
#define PIO_EXECCTRL1_SIDESET_EN_BITS 1
#define PIO_EXECCTRL1_SIDESET_EN_MASK 0x40000000
// Field: EXECCTRL1_SIDE_PINDIR  Access: RW
// If 1, side-set data is asserted to pin directions, instead of pin values.
#define PIO_EXECCTRL1_SIDE_PINDIR_LSB  29
#define PIO_EXECCTRL1_SIDE_PINDIR_BITS 1
#define PIO_EXECCTRL1_SIDE_PINDIR_MASK 0x20000000
// Field: EXECCTRL1_JMP_PIN  Access: RW
// The GPIO number to use as condition for JMP PIN. Unaffected by input mapping.
#define PIO_EXECCTRL1_JMP_PIN_LSB  24
#define PIO_EXECCTRL1_JMP_PIN_BITS 5
#define PIO_EXECCTRL1_JMP_PIN_MASK 0x1f000000
// Field: EXECCTRL1_OUT_EN_SEL  Access: RW
// Which data bit to use for inline OUT enable.
#define PIO_EXECCTRL1_OUT_EN_SEL_LSB  19
#define PIO_EXECCTRL1_OUT_EN_SEL_BITS 5
#define PIO_EXECCTRL1_OUT_EN_SEL_MASK 0xf80000
// Field: EXECCTRL1_INLINE_OUT_EN  Access: RW
// If 1, use a bit of OUT data as an auxiliary write enable When used in
// conjunction with OUT_STICKY, writes with an enable of 0 will deassert the
// latest pin write.
#define PIO_EXECCTRL1_INLINE_OUT_EN_LSB  18
#define PIO_EXECCTRL1_INLINE_OUT_EN_BITS 1
#define PIO_EXECCTRL1_INLINE_OUT_EN_MASK 0x40000
// Field: EXECCTRL1_OUT_STICKY  Access: RW
// Continuously assert the most recent OUT/SET to the pins.
#define PIO_EXECCTRL1_OUT_STICKY_LSB  17
#define PIO_EXECCTRL1_OUT_STICKY_BITS 1
#define PIO_EXECCTRL1_OUT_STICKY_MASK 0x20000
// Field: EXECCTRL1_WRAP_TOP  Access: RW
// After reaching this address, execution is wrapped to wrap_bottom.
#define PIO_EXECCTRL1_WRAP_TOP_LSB  12
#define PIO_EXECCTRL1_WRAP_TOP_BITS 5
#define PIO_EXECCTRL1_WRAP_TOP_MASK 0x1f000
// Field: EXECCTRL1_WRAP_BOTTOM  Access: RW
// After reaching wrap_top, execution is wrapped to this address.
#define PIO_EXECCTRL1_WRAP_BOTTOM_LSB  7
#define PIO_EXECCTRL1_WRAP_BOTTOM_BITS 5
#define PIO_EXECCTRL1_WRAP_BOTTOM_MASK 0xf80
// Field: EXECCTRL1_STATUS_SEL  Access: RW
// Comparison used for the MOV x, STATUS instruction.
#define PIO_EXECCTRL1_STATUS_SEL_LSB  4
#define PIO_EXECCTRL1_STATUS_SEL_BITS 1
#define PIO_EXECCTRL1_STATUS_SEL_MASK 0x10
// Field: EXECCTRL1_STATUS_N  Access: RW
// Comparison level for the MOV x, STATUS instruction.
#define PIO_EXECCTRL1_STATUS_N_LSB  0
#define PIO_EXECCTRL1_STATUS_N_BITS 4
#define PIO_EXECCTRL1_STATUS_N_MASK 0xf

/*******************************************************************************
*                                  SHIFTCTRL1                                  *
*******************************************************************************/

// Control behaviour of the input/output shift registers for state machine

// Field: SHIFTCTRL1_OSR_THRESHOLD  Access: RW
// Pull threshold. Number of bits shifted out of OSR before autopull, or
// conditional pull (PULL IFEMPTY), will take place.
#define PIO_SHIFTCTRL1_OSR_THRESHOLD_LSB  26
#define PIO_SHIFTCTRL1_OSR_THRESHOLD_BITS 6
#define PIO_SHIFTCTRL1_OSR_THRESHOLD_MASK 0xfc000000
// Field: SHIFTCTRL1_ISR_THRESHOLD  Access: RW
// Push threshold. Number of bits shifted into ISR before autopush, or
// conditional push (PUSH IFFULL), will take place.
#define PIO_SHIFTCTRL1_ISR_THRESHOLD_LSB  20
#define PIO_SHIFTCTRL1_ISR_THRESHOLD_BITS 6
#define PIO_SHIFTCTRL1_ISR_THRESHOLD_MASK 0x3f00000
// Field: SHIFTCTRL1_OUT_SHIFT_DIR  Access: RW
// 1 = shift out of output shift register to right. 0 = to left.
#define PIO_SHIFTCTRL1_OUT_SHIFT_DIR_LSB  19
#define PIO_SHIFTCTRL1_OUT_SHIFT_DIR_BITS 1
#define PIO_SHIFTCTRL1_OUT_SHIFT_DIR_MASK 0x80000
// Field: SHIFTCTRL1_IN_SHIFT_DIR  Access: RW
// 1 = shift input shift register to right (data enters from left). 0 = to left.
#define PIO_SHIFTCTRL1_IN_SHIFT_DIR_LSB  18
#define PIO_SHIFTCTRL1_IN_SHIFT_DIR_BITS 1
#define PIO_SHIFTCTRL1_IN_SHIFT_DIR_MASK 0x40000
// Field: SHIFTCTRL1_AUTO_PULL  Access: RW
// Pull automatically when the output shift register is emptied, i.e.
#define PIO_SHIFTCTRL1_AUTO_PULL_LSB  17
#define PIO_SHIFTCTRL1_AUTO_PULL_BITS 1
#define PIO_SHIFTCTRL1_AUTO_PULL_MASK 0x20000
// Field: SHIFTCTRL1_AUTO_PUSH  Access: RW
// Push automatically when the input shift register is filled, i.e.
#define PIO_SHIFTCTRL1_AUTO_PUSH_LSB  16
#define PIO_SHIFTCTRL1_AUTO_PUSH_BITS 1
#define PIO_SHIFTCTRL1_AUTO_PUSH_MASK 0x10000
// Field: SHIFTCTRL1_CLEAR_RXFIFO  Access: WF
// Write 1 to clear RX fifo.
#define PIO_SHIFTCTRL1_CLEAR_RXFIFO_LSB  15
#define PIO_SHIFTCTRL1_CLEAR_RXFIFO_BITS 1
#define PIO_SHIFTCTRL1_CLEAR_RXFIFO_MASK 0x8000
// Field: SHIFTCTRL1_CLEAR_TXFIFO  Access: WF
// Write 1 to clear TX fifo.
#define PIO_SHIFTCTRL1_CLEAR_TXFIFO_LSB  14
#define PIO_SHIFTCTRL1_CLEAR_TXFIFO_BITS 1
#define PIO_SHIFTCTRL1_CLEAR_TXFIFO_MASK 0x4000
// Field: SHIFTCTRL1_TXFIFO_SHADOW_MODE  Access: RW
// Use shadow mode in txfifo.
#define PIO_SHIFTCTRL1_TXFIFO_SHADOW_MODE_LSB  12
#define PIO_SHIFTCTRL1_TXFIFO_SHADOW_MODE_BITS 1
#define PIO_SHIFTCTRL1_TXFIFO_SHADOW_MODE_MASK 0x1000
// Field: SHIFTCTRL1_TXFIFO_SHADOW_UPDATE  Access: RWF
// Use shadow TX FIFO data to update worked TX FIFO data
#define PIO_SHIFTCTRL1_TXFIFO_SHADOW_UPDATE_LSB  11
#define PIO_SHIFTCTRL1_TXFIFO_SHADOW_UPDATE_BITS 1
#define PIO_SHIFTCTRL1_TXFIFO_SHADOW_UPDATE_MASK 0x800
// Field: SHIFTCTRL1_FJOIN_RX  Access: RW
// When 1, RX FIFO steals the TX FIFO’s storage, and becomes twice as deep.
#define PIO_SHIFTCTRL1_FJOIN_RX_LSB  1
#define PIO_SHIFTCTRL1_FJOIN_RX_BITS 1
#define PIO_SHIFTCTRL1_FJOIN_RX_MASK 0x2
// Field: SHIFTCTRL1_FJOIN_TX  Access: RW
// When 1, TX FIFO steals the RX FIFO’s storage, and becomes twice as deep.
#define PIO_SHIFTCTRL1_FJOIN_TX_LSB  0
#define PIO_SHIFTCTRL1_FJOIN_TX_BITS 1
#define PIO_SHIFTCTRL1_FJOIN_TX_MASK 0x1

/*******************************************************************************
*                                    INSTR1                                    *
*******************************************************************************/

// Immediate instruction register

// Field: INSTR1_INSTR  Access: WF
// Instruction to be exec.
#define PIO_INSTR1_INSTR_LSB  0
#define PIO_INSTR1_INSTR_BITS 16
#define PIO_INSTR1_INSTR_MASK 0xffff

/*******************************************************************************
*                                    PUSH1                                     *
*******************************************************************************/

// TX data FIFO for SM1

// Field: PUSH1  Access: WF
#define PIO_PUSH1_LSB  0
#define PIO_PUSH1_BITS 32
#define PIO_PUSH1_MASK 0xffffffff

/*******************************************************************************
*                                    PULL1                                     *
*******************************************************************************/

// RX data FIFO for SM1

// Field: PULL1  Access: RF
#define PIO_PULL1_LSB  0
#define PIO_PULL1_BITS 32
#define PIO_PULL1_MASK 0xffffffff

/*******************************************************************************
*                                    FSTAT1                                    *
*******************************************************************************/

// FIFO status register for SM1

// Field: FSTAT1_TXLEVEL  Access: ROV
#define PIO_FSTAT1_TXLEVEL_LSB  0
#define PIO_FSTAT1_TXLEVEL_BITS 4
#define PIO_FSTAT1_TXLEVEL_MASK 0xf
// Field: FSTAT1_TXFULL  Access: ROV
#define PIO_FSTAT1_TXFULL_LSB  4
#define PIO_FSTAT1_TXFULL_BITS 1
#define PIO_FSTAT1_TXFULL_MASK 0x10
// Field: FSTAT1_TXEMPTY  Access: ROV
#define PIO_FSTAT1_TXEMPTY_LSB  5
#define PIO_FSTAT1_TXEMPTY_BITS 1
#define PIO_FSTAT1_TXEMPTY_MASK 0x20
// Field: FSTAT1_RXLEVEL  Access: ROV
#define PIO_FSTAT1_RXLEVEL_LSB  6
#define PIO_FSTAT1_RXLEVEL_BITS 4
#define PIO_FSTAT1_RXLEVEL_MASK 0x3c0
// Field: FSTAT1_RXFULL  Access: ROV
#define PIO_FSTAT1_RXFULL_LSB  10
#define PIO_FSTAT1_RXFULL_BITS 1
#define PIO_FSTAT1_RXFULL_MASK 0x400
// Field: FSTAT1_RXEMPTY  Access: ROV
#define PIO_FSTAT1_RXEMPTY_LSB  11
#define PIO_FSTAT1_RXEMPTY_BITS 1
#define PIO_FSTAT1_RXEMPTY_MASK 0x800

/*******************************************************************************
*                                    FCTRL1                                    *
*******************************************************************************/

// FIFO control register for SM1

// Field: FCTRL1_TXFIFO_PUSH_INDEX  Access: RWF
// tx fifo push index
#define PIO_FCTRL1_TXFIFO_PUSH_INDEX_LSB  0
#define PIO_FCTRL1_TXFIFO_PUSH_INDEX_BITS 2
#define PIO_FCTRL1_TXFIFO_PUSH_INDEX_MASK 0x3
// Field: FCTRL1_TXFIFO_PULL_INDEX  Access: RWF
// tx fifo pull index
#define PIO_FCTRL1_TXFIFO_PULL_INDEX_LSB  2
#define PIO_FCTRL1_TXFIFO_PULL_INDEX_BITS 2
#define PIO_FCTRL1_TXFIFO_PULL_INDEX_MASK 0xc
// Field: FCTRL1_TXFIFO_READ_EN  Access: RW
// tx fifo read enable
#define PIO_FCTRL1_TXFIFO_READ_EN_LSB  4
#define PIO_FCTRL1_TXFIFO_READ_EN_BITS 1
#define PIO_FCTRL1_TXFIFO_READ_EN_MASK 0x10
// Field: FCTRL1_RXFIFO_PUSH_INDEX  Access: RWF
// rx fifo push index
#define PIO_FCTRL1_RXFIFO_PUSH_INDEX_LSB  5
#define PIO_FCTRL1_RXFIFO_PUSH_INDEX_BITS 2
#define PIO_FCTRL1_RXFIFO_PUSH_INDEX_MASK 0x60
// Field: FCTRL1_RXFIFO_PULL_INDEX  Access: RWF
// rx fifo pull index
#define PIO_FCTRL1_RXFIFO_PULL_INDEX_LSB  7
#define PIO_FCTRL1_RXFIFO_PULL_INDEX_BITS 2
#define PIO_FCTRL1_RXFIFO_PULL_INDEX_MASK 0x180
// Field: FCTRL1_RXFIFO_WRITE_EN  Access: RW
// rx fifo write enable
#define PIO_FCTRL1_RXFIFO_WRITE_EN_LSB  9
#define PIO_FCTRL1_RXFIFO_WRITE_EN_BITS 1
#define PIO_FCTRL1_RXFIFO_WRITE_EN_MASK 0x200
// Field: FCTRL1_TX_FIFO_DATA_COUNT  Access: RWF
// set how many data count in tx fifo
#define PIO_FCTRL1_TX_FIFO_DATA_COUNT_LSB  10
#define PIO_FCTRL1_TX_FIFO_DATA_COUNT_BITS 3
#define PIO_FCTRL1_TX_FIFO_DATA_COUNT_MASK 0x1c00
// Field: FCTRL1_RX_FIFO_DATA_COUNT  Access: RWF
// set how many data count in rx fifo
#define PIO_FCTRL1_RX_FIFO_DATA_COUNT_LSB  13
#define PIO_FCTRL1_RX_FIFO_DATA_COUNT_BITS 3
#define PIO_FCTRL1_RX_FIFO_DATA_COUNT_MASK 0xe000

/*******************************************************************************
*                                   CLKDIV2                                    *
*******************************************************************************/

// SM2 clock divider register

// Field: CLKDIV2_CLKDIV  Access: RW
// Clock divisor register for state machine 2.
#define PIO_CLKDIV2_CLKDIV_LSB  0
#define PIO_CLKDIV2_CLKDIV_BITS 32
#define PIO_CLKDIV2_CLKDIV_MASK 0xffffffff

/*******************************************************************************
*                                   PINCTRL2                                   *
*******************************************************************************/

// State machine 2 pin control register

// Field: PINCTRL2_OUT_BASE  Access: RW
// The lowest-numbered pin that will be affected by an OUT PINS, OUT PINDIRS or
// MOV PINS instruction.
#define PIO_PINCTRL2_OUT_BASE_LSB  0
#define PIO_PINCTRL2_OUT_BASE_BITS 5
#define PIO_PINCTRL2_OUT_BASE_MASK 0x1f
// Field: PINCTRL2_SET_BASE  Access: RW
// The lowest-numbered pin that will be affected by a SET PINS or SET PINDIRS
// instruction.
#define PIO_PINCTRL2_SET_BASE_LSB  5
#define PIO_PINCTRL2_SET_BASE_BITS 5
#define PIO_PINCTRL2_SET_BASE_MASK 0x3e0
// Field: PINCTRL2_SIDE_BASE  Access: RW
// The lowest-numbered pin that will be affected by a side-set operation.
#define PIO_PINCTRL2_SIDE_BASE_LSB  10
#define PIO_PINCTRL2_SIDE_BASE_BITS 5
#define PIO_PINCTRL2_SIDE_BASE_MASK 0x7c00
// Field: PINCTRL2_IN_BASE  Access: RW
// The pin which is mapped to the least-significant bit of a state machine’s IN
// data bus.
#define PIO_PINCTRL2_IN_BASE_LSB  15
#define PIO_PINCTRL2_IN_BASE_BITS 5
#define PIO_PINCTRL2_IN_BASE_MASK 0xf8000
// Field: PINCTRL2_OUT_COUNT  Access: RW
// The number of pins asserted by an OUT PINS, OUT PINDIRS or MOV PINS
// instruction.
#define PIO_PINCTRL2_OUT_COUNT_LSB  20
#define PIO_PINCTRL2_OUT_COUNT_BITS 6
#define PIO_PINCTRL2_OUT_COUNT_MASK 0x3f00000
// Field: PINCTRL2_SET_COUNT  Access: RW
// The number of pins asserted by a SET. In the range 0 to 5 inclusive.
#define PIO_PINCTRL2_SET_COUNT_LSB  26
#define PIO_PINCTRL2_SET_COUNT_BITS 3
#define PIO_PINCTRL2_SET_COUNT_MASK 0x1c000000
// Field: PINCTRL2_SIDE_COUNT  Access: RW
// The number of MSBs of the Delay/Side-set instruction field which are used for
// side-set.
#define PIO_PINCTRL2_SIDE_COUNT_LSB  29
#define PIO_PINCTRL2_SIDE_COUNT_BITS 3
#define PIO_PINCTRL2_SIDE_COUNT_MASK 0xe0000000

/*******************************************************************************
*                                  EXECCTRL2                                   *
*******************************************************************************/

// Execution/behavioural settings register

// Field: EXECCTRL2_EXEC_STALLED  Access: RW
// If 1, an instruction written to INSTR is stalled, and latched by the state
// machine.
#define PIO_EXECCTRL2_EXEC_STALLED_LSB  31
#define PIO_EXECCTRL2_EXEC_STALLED_BITS 1
#define PIO_EXECCTRL2_EXEC_STALLED_MASK 0x80000000
// Field: EXECCTRL2_SIDESET_EN  Access: RW
// If 1, the MSB of the Delay/Side-set instruction field is used as side-set
// enable, rather than a side-set data bit.
#define PIO_EXECCTRL2_SIDESET_EN_LSB  30
#define PIO_EXECCTRL2_SIDESET_EN_BITS 1
#define PIO_EXECCTRL2_SIDESET_EN_MASK 0x40000000
// Field: EXECCTRL2_SIDE_PINDIR  Access: RW
// If 1, side-set data is asserted to pin directions, instead of pin values.
#define PIO_EXECCTRL2_SIDE_PINDIR_LSB  29
#define PIO_EXECCTRL2_SIDE_PINDIR_BITS 1
#define PIO_EXECCTRL2_SIDE_PINDIR_MASK 0x20000000
// Field: EXECCTRL2_JMP_PIN  Access: RW
// The GPIO number to use as condition for JMP PIN. Unaffected by input mapping.
#define PIO_EXECCTRL2_JMP_PIN_LSB  24
#define PIO_EXECCTRL2_JMP_PIN_BITS 5
#define PIO_EXECCTRL2_JMP_PIN_MASK 0x1f000000
// Field: EXECCTRL2_OUT_EN_SEL  Access: RW
// Which data bit to use for inline OUT enable.
#define PIO_EXECCTRL2_OUT_EN_SEL_LSB  19
#define PIO_EXECCTRL2_OUT_EN_SEL_BITS 5
#define PIO_EXECCTRL2_OUT_EN_SEL_MASK 0xf80000
// Field: EXECCTRL2_INLINE_OUT_EN  Access: RW
// If 1, use a bit of OUT data as an auxiliary write enable When used in
// conjunction with OUT_STICKY, writes with an enable of 0 will deassert the
// latest pin write.
#define PIO_EXECCTRL2_INLINE_OUT_EN_LSB  18
#define PIO_EXECCTRL2_INLINE_OUT_EN_BITS 1
#define PIO_EXECCTRL2_INLINE_OUT_EN_MASK 0x40000
// Field: EXECCTRL2_OUT_STICKY  Access: RW
// Continuously assert the most recent OUT/SET to the pins.
#define PIO_EXECCTRL2_OUT_STICKY_LSB  17
#define PIO_EXECCTRL2_OUT_STICKY_BITS 1
#define PIO_EXECCTRL2_OUT_STICKY_MASK 0x20000
// Field: EXECCTRL2_WRAP_TOP  Access: RW
// After reaching this address, execution is wrapped to wrap_bottom.
#define PIO_EXECCTRL2_WRAP_TOP_LSB  12
#define PIO_EXECCTRL2_WRAP_TOP_BITS 5
#define PIO_EXECCTRL2_WRAP_TOP_MASK 0x1f000
// Field: EXECCTRL2_WRAP_BOTTOM  Access: RW
// After reaching wrap_top, execution is wrapped to this address.
#define PIO_EXECCTRL2_WRAP_BOTTOM_LSB  7
#define PIO_EXECCTRL2_WRAP_BOTTOM_BITS 5
#define PIO_EXECCTRL2_WRAP_BOTTOM_MASK 0xf80
// Field: EXECCTRL2_STATUS_SEL  Access: RW
// Comparison used for the MOV x, STATUS instruction.
#define PIO_EXECCTRL2_STATUS_SEL_LSB  4
#define PIO_EXECCTRL2_STATUS_SEL_BITS 1
#define PIO_EXECCTRL2_STATUS_SEL_MASK 0x10
// Field: EXECCTRL2_STATUS_N  Access: RW
// Comparison level for the MOV x, STATUS instruction.
#define PIO_EXECCTRL2_STATUS_N_LSB  0
#define PIO_EXECCTRL2_STATUS_N_BITS 4
#define PIO_EXECCTRL2_STATUS_N_MASK 0xf

/*******************************************************************************
*                                  SHIFTCTRL2                                  *
*******************************************************************************/

// Control behaviour of the input/output shift registers for state machine

// Field: SHIFTCTRL2_OSR_THRESHOLD  Access: RW
// Pull threshold. Number of bits shifted out of OSR before autopull, or
// conditional pull (PULL IFEMPTY), will take place.
#define PIO_SHIFTCTRL2_OSR_THRESHOLD_LSB  26
#define PIO_SHIFTCTRL2_OSR_THRESHOLD_BITS 6
#define PIO_SHIFTCTRL2_OSR_THRESHOLD_MASK 0xfc000000
// Field: SHIFTCTRL2_ISR_THRESHOLD  Access: RW
// Push threshold. Number of bits shifted into ISR before autopush, or
// conditional push (PUSH IFFULL), will take place.
#define PIO_SHIFTCTRL2_ISR_THRESHOLD_LSB  20
#define PIO_SHIFTCTRL2_ISR_THRESHOLD_BITS 6
#define PIO_SHIFTCTRL2_ISR_THRESHOLD_MASK 0x3f00000
// Field: SHIFTCTRL2_OUT_SHIFT_DIR  Access: RW
// 1 = shift out of output shift register to right. 0 = to left.
#define PIO_SHIFTCTRL2_OUT_SHIFT_DIR_LSB  19
#define PIO_SHIFTCTRL2_OUT_SHIFT_DIR_BITS 1
#define PIO_SHIFTCTRL2_OUT_SHIFT_DIR_MASK 0x80000
// Field: SHIFTCTRL2_IN_SHIFT_DIR  Access: RW
// 1 = shift input shift register to right (data enters from left). 0 = to left.
#define PIO_SHIFTCTRL2_IN_SHIFT_DIR_LSB  18
#define PIO_SHIFTCTRL2_IN_SHIFT_DIR_BITS 1
#define PIO_SHIFTCTRL2_IN_SHIFT_DIR_MASK 0x40000
// Field: SHIFTCTRL2_AUTO_PULL  Access: RW
// Pull automatically when the output shift register is emptied, i.e.
#define PIO_SHIFTCTRL2_AUTO_PULL_LSB  17
#define PIO_SHIFTCTRL2_AUTO_PULL_BITS 1
#define PIO_SHIFTCTRL2_AUTO_PULL_MASK 0x20000
// Field: SHIFTCTRL2_AUTO_PUSH  Access: RW
// Push automatically when the input shift register is filled, i.e.
#define PIO_SHIFTCTRL2_AUTO_PUSH_LSB  16
#define PIO_SHIFTCTRL2_AUTO_PUSH_BITS 1
#define PIO_SHIFTCTRL2_AUTO_PUSH_MASK 0x10000
// Field: SHIFTCTRL2_CLEAR_RXFIFO  Access: WF
// Write 1 to clear RX fifo.
#define PIO_SHIFTCTRL2_CLEAR_RXFIFO_LSB  15
#define PIO_SHIFTCTRL2_CLEAR_RXFIFO_BITS 1
#define PIO_SHIFTCTRL2_CLEAR_RXFIFO_MASK 0x8000
// Field: SHIFTCTRL2_CLEAR_TXFIFO  Access: WF
// Write 1 to clear TX fifo.
#define PIO_SHIFTCTRL2_CLEAR_TXFIFO_LSB  14
#define PIO_SHIFTCTRL2_CLEAR_TXFIFO_BITS 1
#define PIO_SHIFTCTRL2_CLEAR_TXFIFO_MASK 0x4000
// Field: SHIFTCTRL2_TXFIFO_SHADOW_MODE  Access: RW
// Use shadow mode in txfifo.
#define PIO_SHIFTCTRL2_TXFIFO_SHADOW_MODE_LSB  12
#define PIO_SHIFTCTRL2_TXFIFO_SHADOW_MODE_BITS 1
#define PIO_SHIFTCTRL2_TXFIFO_SHADOW_MODE_MASK 0x1000
// Field: SHIFTCTRL2_TXFIFO_SHADOW_UPDATE  Access: RWF
// Use shadow TX FIFO data to update worked TX FIFO data
#define PIO_SHIFTCTRL2_TXFIFO_SHADOW_UPDATE_LSB  11
#define PIO_SHIFTCTRL2_TXFIFO_SHADOW_UPDATE_BITS 1
#define PIO_SHIFTCTRL2_TXFIFO_SHADOW_UPDATE_MASK 0x800
// Field: SHIFTCTRL2_FJOIN_RX  Access: RW
// When 1, RX FIFO steals the TX FIFO’s storage, and becomes twice as deep.
#define PIO_SHIFTCTRL2_FJOIN_RX_LSB  1
#define PIO_SHIFTCTRL2_FJOIN_RX_BITS 1
#define PIO_SHIFTCTRL2_FJOIN_RX_MASK 0x2
// Field: SHIFTCTRL2_FJOIN_TX  Access: RW
// When 1, TX FIFO steals the RX FIFO’s storage, and becomes twice as deep.
#define PIO_SHIFTCTRL2_FJOIN_TX_LSB  0
#define PIO_SHIFTCTRL2_FJOIN_TX_BITS 1
#define PIO_SHIFTCTRL2_FJOIN_TX_MASK 0x1

/*******************************************************************************
*                                    INSTR2                                    *
*******************************************************************************/

// Immediate instruction register

// Field: INSTR2_INSTR  Access: WF
// Instruction to be exec.
#define PIO_INSTR2_INSTR_LSB  0
#define PIO_INSTR2_INSTR_BITS 16
#define PIO_INSTR2_INSTR_MASK 0xffff

/*******************************************************************************
*                                    PUSH2                                     *
*******************************************************************************/

// TX data FIFO for SM2

// Field: PUSH2  Access: WF
#define PIO_PUSH2_LSB  0
#define PIO_PUSH2_BITS 32
#define PIO_PUSH2_MASK 0xffffffff

/*******************************************************************************
*                                    PULL2                                     *
*******************************************************************************/

// RX data FIFO for SM2

// Field: PULL2  Access: RF
#define PIO_PULL2_LSB  0
#define PIO_PULL2_BITS 32
#define PIO_PULL2_MASK 0xffffffff

/*******************************************************************************
*                                    FSTAT2                                    *
*******************************************************************************/

// FIFO status register for SM2

// Field: FSTAT2_TXLEVEL  Access: ROV
#define PIO_FSTAT2_TXLEVEL_LSB  0
#define PIO_FSTAT2_TXLEVEL_BITS 4
#define PIO_FSTAT2_TXLEVEL_MASK 0xf
// Field: FSTAT2_TXFULL  Access: ROV
#define PIO_FSTAT2_TXFULL_LSB  4
#define PIO_FSTAT2_TXFULL_BITS 1
#define PIO_FSTAT2_TXFULL_MASK 0x10
// Field: FSTAT2_TXEMPTY  Access: ROV
#define PIO_FSTAT2_TXEMPTY_LSB  5
#define PIO_FSTAT2_TXEMPTY_BITS 1
#define PIO_FSTAT2_TXEMPTY_MASK 0x20
// Field: FSTAT2_RXLEVEL  Access: ROV
#define PIO_FSTAT2_RXLEVEL_LSB  6
#define PIO_FSTAT2_RXLEVEL_BITS 4
#define PIO_FSTAT2_RXLEVEL_MASK 0x3c0
// Field: FSTAT2_RXFULL  Access: ROV
#define PIO_FSTAT2_RXFULL_LSB  10
#define PIO_FSTAT2_RXFULL_BITS 1
#define PIO_FSTAT2_RXFULL_MASK 0x400
// Field: FSTAT2_RXEMPTY  Access: ROV
#define PIO_FSTAT2_RXEMPTY_LSB  11
#define PIO_FSTAT2_RXEMPTY_BITS 1
#define PIO_FSTAT2_RXEMPTY_MASK 0x800

/*******************************************************************************
*                                    FCTRL2                                    *
*******************************************************************************/

// FIFO control register for SM2

// Field: FCTRL2_TXFIFO_PUSH_INDEX  Access: RWF
// tx fifo push index
#define PIO_FCTRL2_TXFIFO_PUSH_INDEX_LSB  0
#define PIO_FCTRL2_TXFIFO_PUSH_INDEX_BITS 2
#define PIO_FCTRL2_TXFIFO_PUSH_INDEX_MASK 0x3
// Field: FCTRL2_TXFIFO_PULL_INDEX  Access: RWF
// tx fifo pull index
#define PIO_FCTRL2_TXFIFO_PULL_INDEX_LSB  2
#define PIO_FCTRL2_TXFIFO_PULL_INDEX_BITS 2
#define PIO_FCTRL2_TXFIFO_PULL_INDEX_MASK 0xc
// Field: FCTRL2_TXFIFO_READ_EN  Access: RW
// tx fifo read enable
#define PIO_FCTRL2_TXFIFO_READ_EN_LSB  4
#define PIO_FCTRL2_TXFIFO_READ_EN_BITS 1
#define PIO_FCTRL2_TXFIFO_READ_EN_MASK 0x10
// Field: FCTRL2_RXFIFO_PUSH_INDEX  Access: RWF
// rx fifo push index
#define PIO_FCTRL2_RXFIFO_PUSH_INDEX_LSB  5
#define PIO_FCTRL2_RXFIFO_PUSH_INDEX_BITS 2
#define PIO_FCTRL2_RXFIFO_PUSH_INDEX_MASK 0x60
// Field: FCTRL2_RXFIFO_PULL_INDEX  Access: RWF
// rx fifo pull index
#define PIO_FCTRL2_RXFIFO_PULL_INDEX_LSB  7
#define PIO_FCTRL2_RXFIFO_PULL_INDEX_BITS 2
#define PIO_FCTRL2_RXFIFO_PULL_INDEX_MASK 0x180
// Field: FCTRL2_RXFIFO_WRITE_EN  Access: RW
// rx fifo write enable
#define PIO_FCTRL2_RXFIFO_WRITE_EN_LSB  9
#define PIO_FCTRL2_RXFIFO_WRITE_EN_BITS 1
#define PIO_FCTRL2_RXFIFO_WRITE_EN_MASK 0x200
// Field: FCTRL2_TX_FIFO_DATA_COUNT  Access: RWF
// set how many data count in tx fifo
#define PIO_FCTRL2_TX_FIFO_DATA_COUNT_LSB  10
#define PIO_FCTRL2_TX_FIFO_DATA_COUNT_BITS 3
#define PIO_FCTRL2_TX_FIFO_DATA_COUNT_MASK 0x1c00
// Field: FCTRL2_RX_FIFO_DATA_COUNT  Access: RWF
// set how many data count in rx fifo
#define PIO_FCTRL2_RX_FIFO_DATA_COUNT_LSB  13
#define PIO_FCTRL2_RX_FIFO_DATA_COUNT_BITS 3
#define PIO_FCTRL2_RX_FIFO_DATA_COUNT_MASK 0xe000

/*******************************************************************************
*                                   CLKDIV3                                    *
*******************************************************************************/

// SM3 clock divider register

// Field: CLKDIV3_CLKDIV  Access: RW
// Clock divisor register for state machine 3.
#define PIO_CLKDIV3_CLKDIV_LSB  0
#define PIO_CLKDIV3_CLKDIV_BITS 32
#define PIO_CLKDIV3_CLKDIV_MASK 0xffffffff

/*******************************************************************************
*                                   PINCTRL3                                   *
*******************************************************************************/

// State machine 3 pin control register

// Field: PINCTRL3_OUT_BASE  Access: RW
// The lowest-numbered pin that will be affected by an OUT PINS, OUT PINDIRS or
// MOV PINS instruction.
#define PIO_PINCTRL3_OUT_BASE_LSB  0
#define PIO_PINCTRL3_OUT_BASE_BITS 5
#define PIO_PINCTRL3_OUT_BASE_MASK 0x1f
// Field: PINCTRL3_SET_BASE  Access: RW
// The lowest-numbered pin that will be affected by a SET PINS or SET PINDIRS
// instruction.
#define PIO_PINCTRL3_SET_BASE_LSB  5
#define PIO_PINCTRL3_SET_BASE_BITS 5
#define PIO_PINCTRL3_SET_BASE_MASK 0x3e0
// Field: PINCTRL3_SIDE_BASE  Access: RW
// The lowest-numbered pin that will be affected by a side-set operation.
#define PIO_PINCTRL3_SIDE_BASE_LSB  10
#define PIO_PINCTRL3_SIDE_BASE_BITS 5
#define PIO_PINCTRL3_SIDE_BASE_MASK 0x7c00
// Field: PINCTRL3_IN_BASE  Access: RW
// The pin which is mapped to the least-significant bit of a state machine’s IN
// data bus.
#define PIO_PINCTRL3_IN_BASE_LSB  15
#define PIO_PINCTRL3_IN_BASE_BITS 5
#define PIO_PINCTRL3_IN_BASE_MASK 0xf8000
// Field: PINCTRL3_OUT_COUNT  Access: RW
// The number of pins asserted by an OUT PINS, OUT PINDIRS or MOV PINS
// instruction.
#define PIO_PINCTRL3_OUT_COUNT_LSB  20
#define PIO_PINCTRL3_OUT_COUNT_BITS 6
#define PIO_PINCTRL3_OUT_COUNT_MASK 0x3f00000
// Field: PINCTRL3_SET_COUNT  Access: RW
// The number of pins asserted by a SET. In the range 0 to 5 inclusive.
#define PIO_PINCTRL3_SET_COUNT_LSB  26
#define PIO_PINCTRL3_SET_COUNT_BITS 3
#define PIO_PINCTRL3_SET_COUNT_MASK 0x1c000000
// Field: PINCTRL3_SIDE_COUNT  Access: RW
// The number of MSBs of the Delay/Side-set instruction field which are used for
// side-set.
#define PIO_PINCTRL3_SIDE_COUNT_LSB  29
#define PIO_PINCTRL3_SIDE_COUNT_BITS 3
#define PIO_PINCTRL3_SIDE_COUNT_MASK 0xe0000000

/*******************************************************************************
*                                  EXECCTRL3                                   *
*******************************************************************************/

// Execution/behavioural settings register

// Field: EXECCTRL3_EXEC_STALLED  Access: RW
// If 1, an instruction written to INSTR is stalled, and latched by the state
// machine.
#define PIO_EXECCTRL3_EXEC_STALLED_LSB  31
#define PIO_EXECCTRL3_EXEC_STALLED_BITS 1
#define PIO_EXECCTRL3_EXEC_STALLED_MASK 0x80000000
// Field: EXECCTRL3_SIDESET_EN  Access: RW
// If 1, the MSB of the Delay/Side-set instruction field is used as side-set
// enable, rather than a side-set data bit.
#define PIO_EXECCTRL3_SIDESET_EN_LSB  30
#define PIO_EXECCTRL3_SIDESET_EN_BITS 1
#define PIO_EXECCTRL3_SIDESET_EN_MASK 0x40000000
// Field: EXECCTRL3_SIDE_PINDIR  Access: RW
// If 1, side-set data is asserted to pin directions, instead of pin values.
#define PIO_EXECCTRL3_SIDE_PINDIR_LSB  29
#define PIO_EXECCTRL3_SIDE_PINDIR_BITS 1
#define PIO_EXECCTRL3_SIDE_PINDIR_MASK 0x20000000
// Field: EXECCTRL3_JMP_PIN  Access: RW
// The GPIO number to use as condition for JMP PIN. Unaffected by input mapping.
#define PIO_EXECCTRL3_JMP_PIN_LSB  24
#define PIO_EXECCTRL3_JMP_PIN_BITS 5
#define PIO_EXECCTRL3_JMP_PIN_MASK 0x1f000000
// Field: EXECCTRL3_OUT_EN_SEL  Access: RW
// Which data bit to use for inline OUT enable.
#define PIO_EXECCTRL3_OUT_EN_SEL_LSB  19
#define PIO_EXECCTRL3_OUT_EN_SEL_BITS 5
#define PIO_EXECCTRL3_OUT_EN_SEL_MASK 0xf80000
// Field: EXECCTRL3_INLINE_OUT_EN  Access: RW
// If 1, use a bit of OUT data as an auxiliary write enable When used in
// conjunction with OUT_STICKY, writes with an enable of 0 will deassert the
// latest pin write.
#define PIO_EXECCTRL3_INLINE_OUT_EN_LSB  18
#define PIO_EXECCTRL3_INLINE_OUT_EN_BITS 1
#define PIO_EXECCTRL3_INLINE_OUT_EN_MASK 0x40000
// Field: EXECCTRL3_OUT_STICKY  Access: RW
// Continuously assert the most recent OUT/SET to the pins.
#define PIO_EXECCTRL3_OUT_STICKY_LSB  17
#define PIO_EXECCTRL3_OUT_STICKY_BITS 1
#define PIO_EXECCTRL3_OUT_STICKY_MASK 0x20000
// Field: EXECCTRL3_WRAP_TOP  Access: RW
// After reaching this address, execution is wrapped to wrap_bottom.
#define PIO_EXECCTRL3_WRAP_TOP_LSB  12
#define PIO_EXECCTRL3_WRAP_TOP_BITS 5
#define PIO_EXECCTRL3_WRAP_TOP_MASK 0x1f000
// Field: EXECCTRL3_WRAP_BOTTOM  Access: RW
// After reaching wrap_top, execution is wrapped to this address.
#define PIO_EXECCTRL3_WRAP_BOTTOM_LSB  7
#define PIO_EXECCTRL3_WRAP_BOTTOM_BITS 5
#define PIO_EXECCTRL3_WRAP_BOTTOM_MASK 0xf80
// Field: EXECCTRL3_STATUS_SEL  Access: RW
// Comparison used for the MOV x, STATUS instruction.
#define PIO_EXECCTRL3_STATUS_SEL_LSB  4
#define PIO_EXECCTRL3_STATUS_SEL_BITS 1
#define PIO_EXECCTRL3_STATUS_SEL_MASK 0x10
// Field: EXECCTRL3_STATUS_N  Access: RW
// Comparison level for the MOV x, STATUS instruction.
#define PIO_EXECCTRL3_STATUS_N_LSB  0
#define PIO_EXECCTRL3_STATUS_N_BITS 4
#define PIO_EXECCTRL3_STATUS_N_MASK 0xf

/*******************************************************************************
*                                  SHIFTCTRL3                                  *
*******************************************************************************/

// Control behaviour of the input/output shift registers for state machine

// Field: SHIFTCTRL3_OSR_THRESHOLD  Access: RW
// Pull threshold. Number of bits shifted out of OSR before autopull, or
// conditional pull (PULL IFEMPTY), will take place.
#define PIO_SHIFTCTRL3_OSR_THRESHOLD_LSB  26
#define PIO_SHIFTCTRL3_OSR_THRESHOLD_BITS 6
#define PIO_SHIFTCTRL3_OSR_THRESHOLD_MASK 0xfc000000
// Field: SHIFTCTRL3_ISR_THRESHOLD  Access: RW
// Push threshold. Number of bits shifted into ISR before autopush, or
// conditional push (PUSH IFFULL), will take place.
#define PIO_SHIFTCTRL3_ISR_THRESHOLD_LSB  20
#define PIO_SHIFTCTRL3_ISR_THRESHOLD_BITS 6
#define PIO_SHIFTCTRL3_ISR_THRESHOLD_MASK 0x3f00000
// Field: SHIFTCTRL3_OUT_SHIFT_DIR  Access: RW
// 1 = shift out of output shift register to right. 0 = to left.
#define PIO_SHIFTCTRL3_OUT_SHIFT_DIR_LSB  19
#define PIO_SHIFTCTRL3_OUT_SHIFT_DIR_BITS 1
#define PIO_SHIFTCTRL3_OUT_SHIFT_DIR_MASK 0x80000
// Field: SHIFTCTRL3_IN_SHIFT_DIR  Access: RW
// 1 = shift input shift register to right (data enters from left). 0 = to left.
#define PIO_SHIFTCTRL3_IN_SHIFT_DIR_LSB  18
#define PIO_SHIFTCTRL3_IN_SHIFT_DIR_BITS 1
#define PIO_SHIFTCTRL3_IN_SHIFT_DIR_MASK 0x40000
// Field: SHIFTCTRL3_AUTO_PULL  Access: RW
// Pull automatically when the output shift register is emptied, i.e.
#define PIO_SHIFTCTRL3_AUTO_PULL_LSB  17
#define PIO_SHIFTCTRL3_AUTO_PULL_BITS 1
#define PIO_SHIFTCTRL3_AUTO_PULL_MASK 0x20000
// Field: SHIFTCTRL3_AUTO_PUSH  Access: RW
// Push automatically when the input shift register is filled, i.e.
#define PIO_SHIFTCTRL3_AUTO_PUSH_LSB  16
#define PIO_SHIFTCTRL3_AUTO_PUSH_BITS 1
#define PIO_SHIFTCTRL3_AUTO_PUSH_MASK 0x10000
// Field: SHIFTCTRL3_CLEAR_RXFIFO  Access: WF
// Write 1 to clear RX fifo.
#define PIO_SHIFTCTRL3_CLEAR_RXFIFO_LSB  15
#define PIO_SHIFTCTRL3_CLEAR_RXFIFO_BITS 1
#define PIO_SHIFTCTRL3_CLEAR_RXFIFO_MASK 0x8000
// Field: SHIFTCTRL3_CLEAR_TXFIFO  Access: WF
// Write 1 to clear TX fifo.
#define PIO_SHIFTCTRL3_CLEAR_TXFIFO_LSB  14
#define PIO_SHIFTCTRL3_CLEAR_TXFIFO_BITS 1
#define PIO_SHIFTCTRL3_CLEAR_TXFIFO_MASK 0x4000
// Field: SHIFTCTRL3_TXFIFO_SHADOW_MODE  Access: RW
// Use shadow mode in txfifo.
#define PIO_SHIFTCTRL3_TXFIFO_SHADOW_MODE_LSB  12
#define PIO_SHIFTCTRL3_TXFIFO_SHADOW_MODE_BITS 1
#define PIO_SHIFTCTRL3_TXFIFO_SHADOW_MODE_MASK 0x1000
// Field: SHIFTCTRL3_TXFIFO_SHADOW_UPDATE  Access: RWF
// Use shadow TX FIFO data to update worked TX FIFO data
#define PIO_SHIFTCTRL3_TXFIFO_SHADOW_UPDATE_LSB  11
#define PIO_SHIFTCTRL3_TXFIFO_SHADOW_UPDATE_BITS 1
#define PIO_SHIFTCTRL3_TXFIFO_SHADOW_UPDATE_MASK 0x800
// Field: SHIFTCTRL3_FJOIN_RX  Access: RW
// When 1, RX FIFO steals the TX FIFO’s storage, and becomes twice as deep.
#define PIO_SHIFTCTRL3_FJOIN_RX_LSB  1
#define PIO_SHIFTCTRL3_FJOIN_RX_BITS 1
#define PIO_SHIFTCTRL3_FJOIN_RX_MASK 0x2
// Field: SHIFTCTRL3_FJOIN_TX  Access: RW
// When 1, TX FIFO steals the RX FIFO’s storage, and becomes twice as deep.
#define PIO_SHIFTCTRL3_FJOIN_TX_LSB  0
#define PIO_SHIFTCTRL3_FJOIN_TX_BITS 1
#define PIO_SHIFTCTRL3_FJOIN_TX_MASK 0x1

/*******************************************************************************
*                                    INSTR3                                    *
*******************************************************************************/

// Immediate instruction register

// Field: INSTR3_INSTR  Access: WF
// Instruction to be exec.
#define PIO_INSTR3_INSTR_LSB  0
#define PIO_INSTR3_INSTR_BITS 16
#define PIO_INSTR3_INSTR_MASK 0xffff

/*******************************************************************************
*                                    PUSH3                                     *
*******************************************************************************/

// TX data FIFO for SM3

// Field: PUSH3  Access: WF
#define PIO_PUSH3_LSB  0
#define PIO_PUSH3_BITS 32
#define PIO_PUSH3_MASK 0xffffffff

/*******************************************************************************
*                                    PULL3                                     *
*******************************************************************************/

// RX data FIFO for SM3

// Field: PULL3  Access: RF
#define PIO_PULL3_LSB  0
#define PIO_PULL3_BITS 32
#define PIO_PULL3_MASK 0xffffffff

/*******************************************************************************
*                                    FSTAT3                                    *
*******************************************************************************/

// FIFO status register for SM3

// Field: FSTAT3_TXLEVEL  Access: ROV
#define PIO_FSTAT3_TXLEVEL_LSB  0
#define PIO_FSTAT3_TXLEVEL_BITS 4
#define PIO_FSTAT3_TXLEVEL_MASK 0xf
// Field: FSTAT3_TXFULL  Access: ROV
#define PIO_FSTAT3_TXFULL_LSB  4
#define PIO_FSTAT3_TXFULL_BITS 1
#define PIO_FSTAT3_TXFULL_MASK 0x10
// Field: FSTAT3_TXEMPTY  Access: ROV
#define PIO_FSTAT3_TXEMPTY_LSB  5
#define PIO_FSTAT3_TXEMPTY_BITS 1
#define PIO_FSTAT3_TXEMPTY_MASK 0x20
// Field: FSTAT3_RXLEVEL  Access: ROV
#define PIO_FSTAT3_RXLEVEL_LSB  6
#define PIO_FSTAT3_RXLEVEL_BITS 4
#define PIO_FSTAT3_RXLEVEL_MASK 0x3c0
// Field: FSTAT3_RXFULL  Access: ROV
#define PIO_FSTAT3_RXFULL_LSB  10
#define PIO_FSTAT3_RXFULL_BITS 1
#define PIO_FSTAT3_RXFULL_MASK 0x400
// Field: FSTAT3_RXEMPTY  Access: ROV
#define PIO_FSTAT3_RXEMPTY_LSB  11
#define PIO_FSTAT3_RXEMPTY_BITS 1
#define PIO_FSTAT3_RXEMPTY_MASK 0x800

/*******************************************************************************
*                                    FCTRL3                                    *
*******************************************************************************/

// FIFO control register for SM3

// Field: FCTRL3_TXFIFO_PUSH_INDEX  Access: RWF
// tx fifo push index
#define PIO_FCTRL3_TXFIFO_PUSH_INDEX_LSB  0
#define PIO_FCTRL3_TXFIFO_PUSH_INDEX_BITS 2
#define PIO_FCTRL3_TXFIFO_PUSH_INDEX_MASK 0x3
// Field: FCTRL3_TXFIFO_PULL_INDEX  Access: RWF
// tx fifo pull index
#define PIO_FCTRL3_TXFIFO_PULL_INDEX_LSB  2
#define PIO_FCTRL3_TXFIFO_PULL_INDEX_BITS 2
#define PIO_FCTRL3_TXFIFO_PULL_INDEX_MASK 0xc
// Field: FCTRL3_TXFIFO_READ_EN  Access: RW
// tx fifo read enable
#define PIO_FCTRL3_TXFIFO_READ_EN_LSB  4
#define PIO_FCTRL3_TXFIFO_READ_EN_BITS 1
#define PIO_FCTRL3_TXFIFO_READ_EN_MASK 0x10
// Field: FCTRL3_RXFIFO_PUSH_INDEX  Access: RWF
// rx fifo push index
#define PIO_FCTRL3_RXFIFO_PUSH_INDEX_LSB  5
#define PIO_FCTRL3_RXFIFO_PUSH_INDEX_BITS 2
#define PIO_FCTRL3_RXFIFO_PUSH_INDEX_MASK 0x60
// Field: FCTRL3_RXFIFO_PULL_INDEX  Access: RWF
// rx fifo pull index
#define PIO_FCTRL3_RXFIFO_PULL_INDEX_LSB  7
#define PIO_FCTRL3_RXFIFO_PULL_INDEX_BITS 2
#define PIO_FCTRL3_RXFIFO_PULL_INDEX_MASK 0x180
// Field: FCTRL3_RXFIFO_WRITE_EN  Access: RW
// rx fifo write enable
#define PIO_FCTRL3_RXFIFO_WRITE_EN_LSB  9
#define PIO_FCTRL3_RXFIFO_WRITE_EN_BITS 1
#define PIO_FCTRL3_RXFIFO_WRITE_EN_MASK 0x200
// Field: FCTRL3_TX_FIFO_DATA_COUNT  Access: RWF
// set how many data count in tx fifo
#define PIO_FCTRL3_TX_FIFO_DATA_COUNT_LSB  10
#define PIO_FCTRL3_TX_FIFO_DATA_COUNT_BITS 3
#define PIO_FCTRL3_TX_FIFO_DATA_COUNT_MASK 0x1c00
// Field: FCTRL3_RX_FIFO_DATA_COUNT  Access: RWF
// set how many data count in rx fifo
#define PIO_FCTRL3_RX_FIFO_DATA_COUNT_LSB  13
#define PIO_FCTRL3_RX_FIFO_DATA_COUNT_BITS 3
#define PIO_FCTRL3_RX_FIFO_DATA_COUNT_MASK 0xe000

/*******************************************************************************
*                                  INSTRMEM0                                   *
*******************************************************************************/

// Instruction 0 register

// Field: INSTRMEM0_INSTR  Access: RW
// Instruction contend.
#define PIO_INSTRMEM0_INSTR_LSB  0
#define PIO_INSTRMEM0_INSTR_BITS 16
#define PIO_INSTRMEM0_INSTR_MASK 0xffff

/*******************************************************************************
*                                  INSTRMEM1                                   *
*******************************************************************************/

// Instruction 1 register

// Field: INSTRMEM1_INSTR  Access: RW
// Instruction contend.
#define PIO_INSTRMEM1_INSTR_LSB  0
#define PIO_INSTRMEM1_INSTR_BITS 16
#define PIO_INSTRMEM1_INSTR_MASK 0xffff

/*******************************************************************************
*                                  INSTRMEM2                                   *
*******************************************************************************/

// Instruction 2 register

// Field: INSTRMEM2_INSTR  Access: RW
// Instruction contend.
#define PIO_INSTRMEM2_INSTR_LSB  0
#define PIO_INSTRMEM2_INSTR_BITS 16
#define PIO_INSTRMEM2_INSTR_MASK 0xffff

/*******************************************************************************
*                                  INSTRMEM3                                   *
*******************************************************************************/

// Instruction 3 register

// Field: INSTRMEM3_INSTR  Access: RW
// Instruction contend.
#define PIO_INSTRMEM3_INSTR_LSB  0
#define PIO_INSTRMEM3_INSTR_BITS 16
#define PIO_INSTRMEM3_INSTR_MASK 0xffff

/*******************************************************************************
*                                  INSTRMEM4                                   *
*******************************************************************************/

// Instruction 4 register

// Field: INSTRMEM4_INSTR  Access: RW
// Instruction contend.
#define PIO_INSTRMEM4_INSTR_LSB  0
#define PIO_INSTRMEM4_INSTR_BITS 16
#define PIO_INSTRMEM4_INSTR_MASK 0xffff

/*******************************************************************************
*                                  INSTRMEM5                                   *
*******************************************************************************/

// Instruction 5 register

// Field: INSTRMEM5_INSTR  Access: RW
// Instruction contend.
#define PIO_INSTRMEM5_INSTR_LSB  0
#define PIO_INSTRMEM5_INSTR_BITS 16
#define PIO_INSTRMEM5_INSTR_MASK 0xffff

/*******************************************************************************
*                                  INSTRMEM6                                   *
*******************************************************************************/

// Instruction 6 register

// Field: INSTRMEM6_INSTR  Access: RW
// Instruction contend.
#define PIO_INSTRMEM6_INSTR_LSB  0
#define PIO_INSTRMEM6_INSTR_BITS 16
#define PIO_INSTRMEM6_INSTR_MASK 0xffff

/*******************************************************************************
*                                  INSTRMEM7                                   *
*******************************************************************************/

// Instruction 7 register

// Field: INSTRMEM7_INSTR  Access: RW
// Instruction contend.
#define PIO_INSTRMEM7_INSTR_LSB  0
#define PIO_INSTRMEM7_INSTR_BITS 16
#define PIO_INSTRMEM7_INSTR_MASK 0xffff

/*******************************************************************************
*                                  INSTRMEM8                                   *
*******************************************************************************/

// Instruction 8 register

// Field: INSTRMEM8_INSTR  Access: RW
// Instruction contend.
#define PIO_INSTRMEM8_INSTR_LSB  0
#define PIO_INSTRMEM8_INSTR_BITS 16
#define PIO_INSTRMEM8_INSTR_MASK 0xffff

/*******************************************************************************
*                                  INSTRMEM9                                   *
*******************************************************************************/

// Instruction 9 register

// Field: INSTRMEM9_INSTR  Access: RW
// Instruction contend.
#define PIO_INSTRMEM9_INSTR_LSB  0
#define PIO_INSTRMEM9_INSTR_BITS 16
#define PIO_INSTRMEM9_INSTR_MASK 0xffff

/*******************************************************************************
*                                  INSTRMEM10                                  *
*******************************************************************************/

// Instruction 10 register

// Field: INSTRMEM10_INSTR  Access: RW
// Instruction contend.
#define PIO_INSTRMEM10_INSTR_LSB  0
#define PIO_INSTRMEM10_INSTR_BITS 16
#define PIO_INSTRMEM10_INSTR_MASK 0xffff

/*******************************************************************************
*                                  INSTRMEM11                                  *
*******************************************************************************/

// Instruction 11 register

// Field: INSTRMEM11_INSTR  Access: RW
// Instruction contend.
#define PIO_INSTRMEM11_INSTR_LSB  0
#define PIO_INSTRMEM11_INSTR_BITS 16
#define PIO_INSTRMEM11_INSTR_MASK 0xffff

/*******************************************************************************
*                                  INSTRMEM12                                  *
*******************************************************************************/

// Instruction 12 register

// Field: INSTRMEM12_INSTR  Access: RW
// Instruction contend.
#define PIO_INSTRMEM12_INSTR_LSB  0
#define PIO_INSTRMEM12_INSTR_BITS 16
#define PIO_INSTRMEM12_INSTR_MASK 0xffff

/*******************************************************************************
*                                  INSTRMEM13                                  *
*******************************************************************************/

// Instruction 13 register

// Field: INSTRMEM13_INSTR  Access: RW
// Instruction contend.
#define PIO_INSTRMEM13_INSTR_LSB  0
#define PIO_INSTRMEM13_INSTR_BITS 16
#define PIO_INSTRMEM13_INSTR_MASK 0xffff

/*******************************************************************************
*                                  INSTRMEM14                                  *
*******************************************************************************/

// Instruction 14 register

// Field: INSTRMEM14_INSTR  Access: RW
// Instruction contend.
#define PIO_INSTRMEM14_INSTR_LSB  0
#define PIO_INSTRMEM14_INSTR_BITS 16
#define PIO_INSTRMEM14_INSTR_MASK 0xffff

/*******************************************************************************
*                                  INSTRMEM15                                  *
*******************************************************************************/

// Instruction 15 register

// Field: INSTRMEM15_INSTR  Access: RW
// Instruction contend.
#define PIO_INSTRMEM15_INSTR_LSB  0
#define PIO_INSTRMEM15_INSTR_BITS 16
#define PIO_INSTRMEM15_INSTR_MASK 0xffff

/*******************************************************************************
*                                  INSTRMEM16                                  *
*******************************************************************************/

// Instruction 16 register

// Field: INSTRMEM16_INSTR  Access: RW
// Instruction contend.
#define PIO_INSTRMEM16_INSTR_LSB  0
#define PIO_INSTRMEM16_INSTR_BITS 16
#define PIO_INSTRMEM16_INSTR_MASK 0xffff

/*******************************************************************************
*                                  INSTRMEM17                                  *
*******************************************************************************/

// Instruction 17 register

// Field: INSTRMEM17_INSTR  Access: RW
// Instruction contend.
#define PIO_INSTRMEM17_INSTR_LSB  0
#define PIO_INSTRMEM17_INSTR_BITS 16
#define PIO_INSTRMEM17_INSTR_MASK 0xffff

/*******************************************************************************
*                                  INSTRMEM18                                  *
*******************************************************************************/

// Instruction 18 register

// Field: INSTRMEM18_INSTR  Access: RW
// Instruction contend.
#define PIO_INSTRMEM18_INSTR_LSB  0
#define PIO_INSTRMEM18_INSTR_BITS 16
#define PIO_INSTRMEM18_INSTR_MASK 0xffff

/*******************************************************************************
*                                  INSTRMEM19                                  *
*******************************************************************************/

// Instruction 19 register

// Field: INSTRMEM19_INSTR  Access: RW
// Instruction contend.
#define PIO_INSTRMEM19_INSTR_LSB  0
#define PIO_INSTRMEM19_INSTR_BITS 16
#define PIO_INSTRMEM19_INSTR_MASK 0xffff

/*******************************************************************************
*                                  INSTRMEM20                                  *
*******************************************************************************/

// Instruction 20 register

// Field: INSTRMEM20_INSTR  Access: RW
// Instruction contend.
#define PIO_INSTRMEM20_INSTR_LSB  0
#define PIO_INSTRMEM20_INSTR_BITS 16
#define PIO_INSTRMEM20_INSTR_MASK 0xffff

/*******************************************************************************
*                                  INSTRMEM21                                  *
*******************************************************************************/

// Instruction 21 register

// Field: INSTRMEM21_INSTR  Access: RW
// Instruction contend.
#define PIO_INSTRMEM21_INSTR_LSB  0
#define PIO_INSTRMEM21_INSTR_BITS 16
#define PIO_INSTRMEM21_INSTR_MASK 0xffff

/*******************************************************************************
*                                  INSTRMEM22                                  *
*******************************************************************************/

// Instruction 22 register

// Field: INSTRMEM22_INSTR  Access: RW
// Instruction contend.
#define PIO_INSTRMEM22_INSTR_LSB  0
#define PIO_INSTRMEM22_INSTR_BITS 16
#define PIO_INSTRMEM22_INSTR_MASK 0xffff

/*******************************************************************************
*                                  INSTRMEM23                                  *
*******************************************************************************/

// Instruction 23 register

// Field: INSTRMEM23_INSTR  Access: RW
// Instruction contend.
#define PIO_INSTRMEM23_INSTR_LSB  0
#define PIO_INSTRMEM23_INSTR_BITS 16
#define PIO_INSTRMEM23_INSTR_MASK 0xffff

/*******************************************************************************
*                                  INSTRMEM24                                  *
*******************************************************************************/

// Instruction 24 register

// Field: INSTRMEM24_INSTR  Access: RW
// Instruction contend.
#define PIO_INSTRMEM24_INSTR_LSB  0
#define PIO_INSTRMEM24_INSTR_BITS 16
#define PIO_INSTRMEM24_INSTR_MASK 0xffff

/*******************************************************************************
*                                  INSTRMEM25                                  *
*******************************************************************************/

// Instruction 25 register

// Field: INSTRMEM25_INSTR  Access: RW
// Instruction contend.
#define PIO_INSTRMEM25_INSTR_LSB  0
#define PIO_INSTRMEM25_INSTR_BITS 16
#define PIO_INSTRMEM25_INSTR_MASK 0xffff

/*******************************************************************************
*                                  INSTRMEM26                                  *
*******************************************************************************/

// Instruction 26 register

// Field: INSTRMEM26_INSTR  Access: RW
// Instruction contend.
#define PIO_INSTRMEM26_INSTR_LSB  0
#define PIO_INSTRMEM26_INSTR_BITS 16
#define PIO_INSTRMEM26_INSTR_MASK 0xffff

/*******************************************************************************
*                                  INSTRMEM27                                  *
*******************************************************************************/

// Instruction 27 register

// Field: INSTRMEM27_INSTR  Access: RW
// Instruction contend.
#define PIO_INSTRMEM27_INSTR_LSB  0
#define PIO_INSTRMEM27_INSTR_BITS 16
#define PIO_INSTRMEM27_INSTR_MASK 0xffff

/*******************************************************************************
*                                  INSTRMEM28                                  *
*******************************************************************************/

// Instruction 28 register

// Field: INSTRMEM28_INSTR  Access: RW
// Instruction contend.
#define PIO_INSTRMEM28_INSTR_LSB  0
#define PIO_INSTRMEM28_INSTR_BITS 16
#define PIO_INSTRMEM28_INSTR_MASK 0xffff

/*******************************************************************************
*                                  INSTRMEM29                                  *
*******************************************************************************/

// Instruction 29 register

// Field: INSTRMEM29_INSTR  Access: RW
// Instruction contend.
#define PIO_INSTRMEM29_INSTR_LSB  0
#define PIO_INSTRMEM29_INSTR_BITS 16
#define PIO_INSTRMEM29_INSTR_MASK 0xffff

/*******************************************************************************
*                                  INSTRMEM30                                  *
*******************************************************************************/

// Instruction 30 register

// Field: INSTRMEM30_INSTR  Access: RW
// Instruction contend.
#define PIO_INSTRMEM30_INSTR_LSB  0
#define PIO_INSTRMEM30_INSTR_BITS 16
#define PIO_INSTRMEM30_INSTR_MASK 0xffff

/*******************************************************************************
*                                  INSTRMEM31                                  *
*******************************************************************************/

// Instruction 31 register

// Field: INSTRMEM31_INSTR  Access: RW
// Instruction contend.
#define PIO_INSTRMEM31_INSTR_LSB  0
#define PIO_INSTRMEM31_INSTR_BITS 16
#define PIO_INSTRMEM31_INSTR_MASK 0xffff

#endif // _PIO_REGS_H_
