/*******************************************************************************
*                          AUTOGENERATED BY REGBLOCK                           *
*                            Do not edit manually.                             *
*          Edit the source file (or regblock utility) and regenerate.          *
*******************************************************************************/

// Block name           : tfpu
// Bus type             : apb
// Bus data width       : 32
// Bus address width    : 16

module tfpu_regs (
	input wire clk,
	input wire rst_n,
	
	// APB Port
	input wire apbs_psel,
	input wire apbs_penable,
	input wire apbs_pwrite,
	input wire [15:0] apbs_paddr,
	input wire [31:0] apbs_pwdata,
	output wire [31:0] apbs_prdata,
	output wire apbs_pready,
	output wire apbs_pslverr,
	
	// Register interfaces
	output reg [3:0] csr_op_o,
	input wire  csr_start_i,
	output reg  csr_start_o,
	output reg csr_start_wen,
	output reg csr_start_ren,
	output reg [31:0] op_a_o,
	output reg [31:0] op_b_o,
	input wire [31:0] res_z_i,
	output reg res_z_ren
);

// APB adapter
wire [31:0] wdata = apbs_pwdata;
reg [31:0] rdata;
wire wen = apbs_psel && apbs_penable && apbs_pwrite;
wire ren = apbs_psel && apbs_penable && !apbs_pwrite;
wire [15:0] addr = apbs_paddr & 16'hc;
assign apbs_prdata = rdata;
assign apbs_pready = 1'b1;
assign apbs_pslverr = 1'b0;

localparam ADDR_CSR = 0;
localparam ADDR_OP_A = 4;
localparam ADDR_OP_B = 8;
localparam ADDR_RES_Z = 12;

wire __csr_wen = wen && addr == ADDR_CSR;
wire __csr_ren = ren && addr == ADDR_CSR;
wire __op_a_wen = wen && addr == ADDR_OP_A;
wire __op_a_ren = ren && addr == ADDR_OP_A;
wire __op_b_wen = wen && addr == ADDR_OP_B;
wire __op_b_ren = ren && addr == ADDR_OP_B;
wire __res_z_wen = wen && addr == ADDR_RES_Z;
wire __res_z_ren = ren && addr == ADDR_RES_Z;

wire [3:0] csr_op_wdata = wdata[4:1];
wire [3:0] csr_op_rdata;
wire  csr_start_wdata = wdata[0];
wire  csr_start_rdata;
wire [31:0] __csr_rdata = {27'h0, csr_op_rdata, csr_start_rdata};
assign csr_op_rdata = csr_op_o;
assign csr_start_rdata = csr_start_i;

wire [31:0] op_a_wdata = wdata[31:0];
wire [31:0] op_a_rdata;
wire [31:0] __op_a_rdata = {op_a_rdata};
assign op_a_rdata = op_a_o;

wire [31:0] op_b_wdata = wdata[31:0];
wire [31:0] op_b_rdata;
wire [31:0] __op_b_rdata = {op_b_rdata};
assign op_b_rdata = op_b_o;

wire [31:0] res_z_wdata = wdata[31:0];
wire [31:0] res_z_rdata;
wire [31:0] __res_z_rdata = {res_z_rdata};
assign res_z_rdata = res_z_i;

always @ (*) begin
	case (addr)
		ADDR_CSR: rdata = __csr_rdata;
		ADDR_OP_A: rdata = __op_a_rdata;
		ADDR_OP_B: rdata = __op_b_rdata;
		ADDR_RES_Z: rdata = __res_z_rdata;
		default: rdata = 32'h0;
	endcase
	csr_start_wen = __csr_wen;
	csr_start_o = csr_start_wdata;
	csr_start_ren = __csr_ren;
	res_z_ren = __res_z_ren;
end

always @ (posedge clk or negedge rst_n) begin
	if (!rst_n) begin
		csr_op_o <= 4'h0;
		op_a_o <= 32'h0;
		op_b_o <= 32'h0;
	end else begin
		if (__csr_wen)
			csr_op_o <= csr_op_wdata;
		if (__op_a_wen)
			op_a_o <= op_a_wdata;
		if (__op_b_wen)
			op_b_o <= op_b_wdata;
	end
end

endmodule
