/*******************************************************************************
*                          AUTOGENERATED BY REGBLOCK                           *
*                            Do not edit manually.                             *
*          Edit the source file (or regblock utility) and regenerate.          *
*******************************************************************************/

#ifndef _TFPU_REGS_H_
#define _TFPU_REGS_H_

// Block name           : tfpu
// Bus type             : apb
// Bus data width       : 32
// Bus address width    : 16

#define TFPU_CSR_OFFS 0
#define TFPU_OP_A_OFFS 4
#define TFPU_OP_B_OFFS 8
#define TFPU_RES_Z_OFFS 12

/*******************************************************************************
*                                     CSR                                      *
*******************************************************************************/

// Control and status register

// Field: CSR_OP  Access: RW
// Operate type
#define TFPU_CSR_OP_LSB  1
#define TFPU_CSR_OP_BITS 4
#define TFPU_CSR_OP_MASK 0x1e
// Field: CSR_START  Access: RWF
// Write 1 to start op, self clear when completed.
#define TFPU_CSR_START_LSB  0
#define TFPU_CSR_START_BITS 1
#define TFPU_CSR_START_MASK 0x1

/*******************************************************************************
*                                     OP_A                                     *
*******************************************************************************/

// Operand a register

// Field: OP_A  Access: RW
#define TFPU_OP_A_LSB  0
#define TFPU_OP_A_BITS 32
#define TFPU_OP_A_MASK 0xffffffff

/*******************************************************************************
*                                     OP_B                                     *
*******************************************************************************/

// Operand b register

// Field: OP_B  Access: RW
#define TFPU_OP_B_LSB  0
#define TFPU_OP_B_BITS 32
#define TFPU_OP_B_MASK 0xffffffff

/*******************************************************************************
*                                    RES_Z                                     *
*******************************************************************************/

// Operand result register

// Field: RES_Z  Access: RF
#define TFPU_RES_Z_LSB  0
#define TFPU_RES_Z_BITS 32
#define TFPU_RES_Z_MASK 0xffffffff

#endif // _TFPU_REGS_H_
