/*******************************************************************************
*                          AUTOGENERATED BY REGBLOCK                           *
*                            Do not edit manually.                             *
*          Edit the source file (or regblock utility) and regenerate.          *
*******************************************************************************/

// Block name           : sysinfo
// Bus type             : apb
// Bus data width       : 32
// Bus address width    : 16

module sysinfo_regs (
	input wire clk,
	input wire rst_n,
	
	// APB Port
	input wire apbs_psel,
	input wire apbs_penable,
	input wire apbs_pwrite,
	input wire [15:0] apbs_paddr,
	input wire [31:0] apbs_pwdata,
	output wire [31:0] apbs_prdata,
	output wire apbs_pready,
	output wire apbs_pslverr
	
	// Register interfaces
);

// APB adapter
wire [31:0] wdata = apbs_pwdata;
reg [31:0] rdata;
wire wen = apbs_psel && apbs_penable && apbs_pwrite;
wire ren = apbs_psel && apbs_penable && !apbs_pwrite;
wire [15:0] addr = apbs_paddr & 16'h4;
assign apbs_prdata = rdata;
assign apbs_pready = 1'b1;
assign apbs_pslverr = 1'b0;

localparam ADDR_CHIP_ID = 0;
localparam ADDR_PLATFORM = 4;

wire __chip_id_wen = wen && addr == ADDR_CHIP_ID;
wire __chip_id_ren = ren && addr == ADDR_CHIP_ID;
wire __platform_wen = wen && addr == ADDR_PLATFORM;
wire __platform_ren = ren && addr == ADDR_PLATFORM;

wire [3:0] chip_id_revision_wdata = wdata[31:28];
wire [3:0] chip_id_revision_rdata;
wire [15:0] chip_id_part_wdata = wdata[27:12];
wire [15:0] chip_id_part_rdata;
wire [11:0] chip_id_manufacturer_wdata = wdata[11:0];
wire [11:0] chip_id_manufacturer_rdata;
wire [31:0] __chip_id_rdata = {chip_id_revision_rdata, chip_id_part_rdata, chip_id_manufacturer_rdata};
assign chip_id_revision_rdata = 4'h1;
assign chip_id_part_rdata = 16'h1234;
assign chip_id_manufacturer_rdata = 12'habc;

wire  platform_asic_wdata = wdata[0];
wire  platform_asic_rdata;
wire [31:0] __platform_rdata = {31'h0, platform_asic_rdata};
assign platform_asic_rdata = 1'h0;

always @ (*) begin
	case (addr)
		ADDR_CHIP_ID: rdata = __chip_id_rdata;
		ADDR_PLATFORM: rdata = __platform_rdata;
		default: rdata = 32'h0;
	endcase
end

always @ (posedge clk or negedge rst_n) begin
	if (!rst_n) begin
	end else begin
	end
end

endmodule
