/*******************************************************************************
*                          AUTOGENERATED BY REGBLOCK                           *
*                            Do not edit manually.                             *
*          Edit the source file (or regblock utility) and regenerate.          *
*******************************************************************************/

#ifndef _SYSINFO_REGS_H_
#define _SYSINFO_REGS_H_

// Block name           : sysinfo
// Bus type             : apb
// Bus data width       : 32
// Bus address width    : 16

#define SYSINFO_CHIP_ID_OFFS 0
#define SYSINFO_PLATFORM_OFFS 4

/*******************************************************************************
*                                   CHIP_ID                                    *
*******************************************************************************/

// JEDEC JEP-106 compliant chip identifier

// Field: CHIP_ID_REVISION  Access: RO
#define SYSINFO_CHIP_ID_REVISION_LSB  28
#define SYSINFO_CHIP_ID_REVISION_BITS 4
#define SYSINFO_CHIP_ID_REVISION_MASK 0xf0000000
// Field: CHIP_ID_PART  Access: RO
#define SYSINFO_CHIP_ID_PART_LSB  12
#define SYSINFO_CHIP_ID_PART_BITS 16
#define SYSINFO_CHIP_ID_PART_MASK 0xffff000
// Field: CHIP_ID_MANUFACTURER  Access: RO
#define SYSINFO_CHIP_ID_MANUFACTURER_LSB  0
#define SYSINFO_CHIP_ID_MANUFACTURER_BITS 12
#define SYSINFO_CHIP_ID_MANUFACTURER_MASK 0xfff

/*******************************************************************************
*                                   PLATFORM                                   *
*******************************************************************************/

// Allows software to know what environment it is running in

// Field: PLATFORM_ASIC  Access: RO
// 0: FPGA, 1: ASIC
#define SYSINFO_PLATFORM_ASIC_LSB  0
#define SYSINFO_PLATFORM_ASIC_BITS 1
#define SYSINFO_PLATFORM_ASIC_MASK 0x1

#endif // _SYSINFO_REGS_H_
