/*******************************************************************************
*                          AUTOGENERATED BY REGBLOCK                           *
*                            Do not edit manually.                             *
*          Edit the source file (or regblock utility) and regenerate.          *
*******************************************************************************/

// Block name           : perireset
// Bus type             : apb
// Bus data width       : 32
// Bus address width    : 16

module perireset_regs (
	input wire clk,
	input wire rst_n,
	
	// APB Port
	input wire apbs_psel,
	input wire apbs_penable,
	input wire apbs_pwrite,
	input wire [15:0] apbs_paddr,
	input wire [31:0] apbs_pwdata,
	output wire [31:0] apbs_prdata,
	output wire apbs_pready,
	output wire apbs_pslverr,
	
	// Register interfaces
	input wire [15:0] ctrl_reset_i,
	output reg [15:0] ctrl_reset_o,
	output reg ctrl_reset_wen,
	output reg ctrl_reset_ren
);

// APB adapter
wire [31:0] wdata = apbs_pwdata;
reg [31:0] rdata;
wire wen = apbs_psel && apbs_penable && apbs_pwrite;
wire ren = apbs_psel && apbs_penable && !apbs_pwrite;
wire [15:0] addr = apbs_paddr & 16'h0;
assign apbs_prdata = rdata;
assign apbs_pready = 1'b1;
assign apbs_pslverr = 1'b0;

localparam ADDR_CTRL = 0;

wire __ctrl_wen = wen && addr == ADDR_CTRL;
wire __ctrl_ren = ren && addr == ADDR_CTRL;

wire [15:0] ctrl_reset_wdata = wdata[15:0];
wire [15:0] ctrl_reset_rdata;
wire [31:0] __ctrl_rdata = {16'h0, ctrl_reset_rdata};
assign ctrl_reset_rdata = ctrl_reset_i;

always @ (*) begin
	case (addr)
		ADDR_CTRL: rdata = __ctrl_rdata;
		default: rdata = 32'h0;
	endcase
	ctrl_reset_wen = __ctrl_wen;
	ctrl_reset_o = ctrl_reset_wdata;
	ctrl_reset_ren = __ctrl_ren;
end

always @ (posedge clk or negedge rst_n) begin
	if (!rst_n) begin
	end else begin
	end
end

endmodule
