/*******************************************************************************
*                          AUTOGENERATED BY REGBLOCK                           *
*                            Do not edit manually.                             *
*          Edit the source file (or regblock utility) and regenerate.          *
*******************************************************************************/

#ifndef _PERIRESET_REGS_H_
#define _PERIRESET_REGS_H_

// Block name           : perireset
// Bus type             : apb
// Bus data width       : 32
// Bus address width    : 16

#define PERIRESET_CTRL_OFFS 0

/*******************************************************************************
*                                     CTRL                                     *
*******************************************************************************/

// peris reset control register

// Field: CTRL_RESET  Access: RWF
// Write 1 to reset peri, and self cleared when reset done.
#define PERIRESET_CTRL_RESET_LSB  0
#define PERIRESET_CTRL_RESET_BITS 16
#define PERIRESET_CTRL_RESET_MASK 0xffff

#endif // _PERIRESET_REGS_H_
