/*******************************************************************************
*                          AUTOGENERATED BY REGBLOCK                           *
*                            Do not edit manually.                             *
*          Edit the source file (or regblock utility) and regenerate.          *
*******************************************************************************/

#ifndef _CRC_REGS_H_
#define _CRC_REGS_H_

// Block name           : crc
// Bus type             : apb
// Bus data width       : 32
// Bus address width    : 16

#define CRC_CTRL_OFFS 0
#define CRC_STAT_OFFS 4
#define CRC_INIT_OFFS 8
#define CRC_POLY_OFFS 12
#define CRC_RESULT_OFFS 16
#define CRC_DATA_OFFS 20

/*******************************************************************************
*                                     CTRL                                     *
*******************************************************************************/

// Control register

// Field: CTRL_ENABLE  Access: RW
// 1: enable crc module
#define CRC_CTRL_ENABLE_LSB  0
#define CRC_CTRL_ENABLE_BITS 1
#define CRC_CTRL_ENABLE_MASK 0x1

/*******************************************************************************
*                                     STAT                                     *
*******************************************************************************/

// Status register

// Field: STAT_IDLE  Access: RF
// 1: No data is calculating...
#define CRC_STAT_IDLE_LSB  0
#define CRC_STAT_IDLE_BITS 1
#define CRC_STAT_IDLE_MASK 0x1
// Field: STAT_FIFO_EMPTY  Access: RF
// 1: empty
#define CRC_STAT_FIFO_EMPTY_LSB  1
#define CRC_STAT_FIFO_EMPTY_BITS 1
#define CRC_STAT_FIFO_EMPTY_MASK 0x2
// Field: STAT_FIFO_FULL  Access: RF
// 1: full
#define CRC_STAT_FIFO_FULL_LSB  2
#define CRC_STAT_FIFO_FULL_BITS 1
#define CRC_STAT_FIFO_FULL_MASK 0x4

/*******************************************************************************
*                                     INIT                                     *
*******************************************************************************/

// crc init value register

// Field: INIT_INIT  Access: RW
#define CRC_INIT_INIT_LSB  0
#define CRC_INIT_INIT_BITS 32
#define CRC_INIT_INIT_MASK 0xffffffff

/*******************************************************************************
*                                     POLY                                     *
*******************************************************************************/

// crc poly register

// Field: POLY_POLY  Access: RW
#define CRC_POLY_POLY_LSB  0
#define CRC_POLY_POLY_BITS 32
#define CRC_POLY_POLY_MASK 0xffffffff

/*******************************************************************************
*                                    RESULT                                    *
*******************************************************************************/

// crc result register

// Field: RESULT_RESULT  Access: RF
#define CRC_RESULT_RESULT_LSB  0
#define CRC_RESULT_RESULT_BITS 32
#define CRC_RESULT_RESULT_MASK 0xffffffff

/*******************************************************************************
*                                     DATA                                     *
*******************************************************************************/

// Input data FIFO

// Field: DATA  Access: WF
#define CRC_DATA_LSB  0
#define CRC_DATA_BITS 8
#define CRC_DATA_MASK 0xff

#endif // _CRC_REGS_H_
