/*******************************************************************************
*                          AUTOGENERATED BY REGBLOCK                           *
*                            Do not edit manually.                             *
*          Edit the source file (or regblock utility) and regenerate.          *
*******************************************************************************/

// Block name           : crc
// Bus type             : apb
// Bus data width       : 32
// Bus address width    : 16

module crc_regs (
	input wire clk,
	input wire rst_n,
	
	// APB Port
	input wire apbs_psel,
	input wire apbs_penable,
	input wire apbs_pwrite,
	input wire [15:0] apbs_paddr,
	input wire [31:0] apbs_pwdata,
	output wire [31:0] apbs_prdata,
	output wire apbs_pready,
	output wire apbs_pslverr,
	
	// Register interfaces
	output reg  ctrl_enable_o,
	input wire  stat_idle_i,
	output reg stat_idle_ren,
	input wire  stat_fifo_empty_i,
	output reg stat_fifo_empty_ren,
	input wire  stat_fifo_full_i,
	output reg stat_fifo_full_ren,
	output reg [31:0] init_init_o,
	output reg [31:0] poly_poly_o,
	input wire [31:0] result_result_i,
	output reg result_result_ren,
	output reg [7:0] data_o,
	output reg data_wen
);

// APB adapter
wire [31:0] wdata = apbs_pwdata;
reg [31:0] rdata;
wire wen = apbs_psel && apbs_penable && apbs_pwrite;
wire ren = apbs_psel && apbs_penable && !apbs_pwrite;
wire [15:0] addr = apbs_paddr & 16'h1c;
assign apbs_prdata = rdata;
assign apbs_pready = 1'b1;
assign apbs_pslverr = 1'b0;

localparam ADDR_CTRL = 0;
localparam ADDR_STAT = 4;
localparam ADDR_INIT = 8;
localparam ADDR_POLY = 12;
localparam ADDR_RESULT = 16;
localparam ADDR_DATA = 20;

wire __ctrl_wen = wen && addr == ADDR_CTRL;
wire __ctrl_ren = ren && addr == ADDR_CTRL;
wire __stat_wen = wen && addr == ADDR_STAT;
wire __stat_ren = ren && addr == ADDR_STAT;
wire __init_wen = wen && addr == ADDR_INIT;
wire __init_ren = ren && addr == ADDR_INIT;
wire __poly_wen = wen && addr == ADDR_POLY;
wire __poly_ren = ren && addr == ADDR_POLY;
wire __result_wen = wen && addr == ADDR_RESULT;
wire __result_ren = ren && addr == ADDR_RESULT;
wire __data_wen = wen && addr == ADDR_DATA;
wire __data_ren = ren && addr == ADDR_DATA;

wire  ctrl_enable_wdata = wdata[0];
wire  ctrl_enable_rdata;
wire [31:0] __ctrl_rdata = {31'h0, ctrl_enable_rdata};
assign ctrl_enable_rdata = ctrl_enable_o;

wire  stat_idle_wdata = wdata[0];
wire  stat_idle_rdata;
wire  stat_fifo_empty_wdata = wdata[1];
wire  stat_fifo_empty_rdata;
wire  stat_fifo_full_wdata = wdata[2];
wire  stat_fifo_full_rdata;
wire [31:0] __stat_rdata = {29'h0, stat_fifo_full_rdata, stat_fifo_empty_rdata, stat_idle_rdata};
assign stat_idle_rdata = stat_idle_i;
assign stat_fifo_empty_rdata = stat_fifo_empty_i;
assign stat_fifo_full_rdata = stat_fifo_full_i;

wire [31:0] init_init_wdata = wdata[31:0];
wire [31:0] init_init_rdata;
wire [31:0] __init_rdata = {init_init_rdata};
assign init_init_rdata = init_init_o;

wire [31:0] poly_poly_wdata = wdata[31:0];
wire [31:0] poly_poly_rdata;
wire [31:0] __poly_rdata = {poly_poly_rdata};
assign poly_poly_rdata = poly_poly_o;

wire [31:0] result_result_wdata = wdata[31:0];
wire [31:0] result_result_rdata;
wire [31:0] __result_rdata = {result_result_rdata};
assign result_result_rdata = result_result_i;

wire [7:0] data_wdata = wdata[7:0];
wire [7:0] data_rdata;
wire [31:0] __data_rdata = {24'h0, data_rdata};
assign data_rdata = 8'h0;

always @ (*) begin
	case (addr)
		ADDR_CTRL: rdata = __ctrl_rdata;
		ADDR_STAT: rdata = __stat_rdata;
		ADDR_INIT: rdata = __init_rdata;
		ADDR_POLY: rdata = __poly_rdata;
		ADDR_RESULT: rdata = __result_rdata;
		ADDR_DATA: rdata = __data_rdata;
		default: rdata = 32'h0;
	endcase
	stat_idle_ren = __stat_ren;
	stat_fifo_empty_ren = __stat_ren;
	stat_fifo_full_ren = __stat_ren;
	result_result_ren = __result_ren;
	data_wen = __data_wen;
	data_o = data_wdata;
end

always @ (posedge clk or negedge rst_n) begin
	if (!rst_n) begin
		ctrl_enable_o <= 1'h0;
		init_init_o <= 32'h0;
		poly_poly_o <= 32'h0;
	end else begin
		if (__ctrl_wen)
			ctrl_enable_o <= ctrl_enable_wdata;
		if (__init_wen)
			init_init_o <= init_init_wdata;
		if (__poly_wen)
			poly_poly_o <= poly_poly_wdata;
	end
end

endmodule
