/*******************************************************************************
*                          AUTOGENERATED BY REGBLOCK                           *
*                            Do not edit manually.                             *
*          Edit the source file (or regblock utility) and regenerate.          *
*******************************************************************************/

// Block name           : sdadc
// Bus type             : apb
// Bus data width       : 32
// Bus address width    : 16

module sdadc_regs (
	input wire clk,
	input wire rst_n,
	
	// APB Port
	input wire apbs_psel,
	input wire apbs_penable,
	input wire apbs_pwrite,
	input wire [15:0] apbs_paddr,
	input wire [31:0] apbs_pwdata,
	output wire [31:0] apbs_prdata,
	output wire apbs_pready,
	output wire apbs_pslverr,
	
	// Register interfaces
	output reg [2:0] csr_adc_ava_o,
	input wire  csr_rst_fifo_i,
	output reg  csr_rst_fifo_o,
	output reg csr_rst_fifo_wen,
	output reg csr_rst_fifo_ren,
	input wire  csr_fifo_full_i,
	input wire  csr_fifo_empty_i,
	input wire  csr_int_pend_i,
	output reg  csr_int_pend_o,
	output reg csr_int_pend_wen,
	output reg csr_int_pend_ren,
	output reg  csr_int_en_o,
	output reg  csr_enable_o,
	output reg [7:0] div_o,
	input wire [15:0] data_i,
	output reg data_ren
);

// APB adapter
wire [31:0] wdata = apbs_pwdata;
reg [31:0] rdata;
wire wen = apbs_psel && apbs_penable && apbs_pwrite;
wire ren = apbs_psel && apbs_penable && !apbs_pwrite;
wire [15:0] addr = apbs_paddr & 16'hc;
assign apbs_prdata = rdata;
assign apbs_pready = 1'b1;
assign apbs_pslverr = 1'b0;

localparam ADDR_CSR = 0;
localparam ADDR_DIV = 4;
localparam ADDR_DATA = 8;

wire __csr_wen = wen && addr == ADDR_CSR;
wire __csr_ren = ren && addr == ADDR_CSR;
wire __div_wen = wen && addr == ADDR_DIV;
wire __div_ren = ren && addr == ADDR_DIV;
wire __data_wen = wen && addr == ADDR_DATA;
wire __data_ren = ren && addr == ADDR_DATA;

wire [2:0] csr_adc_ava_wdata = wdata[8:6];
wire [2:0] csr_adc_ava_rdata;
wire  csr_rst_fifo_wdata = wdata[5];
wire  csr_rst_fifo_rdata;
wire  csr_fifo_full_wdata = wdata[4];
wire  csr_fifo_full_rdata;
wire  csr_fifo_empty_wdata = wdata[3];
wire  csr_fifo_empty_rdata;
wire  csr_int_pend_wdata = wdata[2];
wire  csr_int_pend_rdata;
wire  csr_int_en_wdata = wdata[1];
wire  csr_int_en_rdata;
wire  csr_enable_wdata = wdata[0];
wire  csr_enable_rdata;
wire [31:0] __csr_rdata = {23'h0, csr_adc_ava_rdata, csr_rst_fifo_rdata, csr_fifo_full_rdata, csr_fifo_empty_rdata, csr_int_pend_rdata, csr_int_en_rdata, csr_enable_rdata};
assign csr_adc_ava_rdata = csr_adc_ava_o;
assign csr_rst_fifo_rdata = csr_rst_fifo_i;
assign csr_fifo_full_rdata = csr_fifo_full_i;
assign csr_fifo_empty_rdata = csr_fifo_empty_i;
assign csr_int_pend_rdata = csr_int_pend_i;
assign csr_int_en_rdata = csr_int_en_o;
assign csr_enable_rdata = csr_enable_o;

wire [7:0] div_wdata = wdata[7:0];
wire [7:0] div_rdata;
wire [31:0] __div_rdata = {24'h0, div_rdata};
assign div_rdata = div_o;

wire [15:0] data_wdata = wdata[15:0];
wire [15:0] data_rdata;
wire [31:0] __data_rdata = {16'h0, data_rdata};
assign data_rdata = data_i;

always @ (*) begin
	case (addr)
		ADDR_CSR: rdata = __csr_rdata;
		ADDR_DIV: rdata = __div_rdata;
		ADDR_DATA: rdata = __data_rdata;
		default: rdata = 32'h0;
	endcase
	csr_rst_fifo_wen = __csr_wen;
	csr_rst_fifo_o = csr_rst_fifo_wdata;
	csr_rst_fifo_ren = __csr_ren;
	csr_int_pend_wen = __csr_wen;
	csr_int_pend_o = csr_int_pend_wdata;
	csr_int_pend_ren = __csr_ren;
	data_ren = __data_ren;
end

always @ (posedge clk or negedge rst_n) begin
	if (!rst_n) begin
		csr_adc_ava_o <= 3'h3;
		csr_int_en_o <= 1'h0;
		csr_enable_o <= 1'h0;
		div_o <= 8'h1;
	end else begin
		if (__csr_wen)
			csr_adc_ava_o <= csr_adc_ava_wdata;
		if (__csr_wen)
			csr_int_en_o <= csr_int_en_wdata;
		if (__csr_wen)
			csr_enable_o <= csr_enable_wdata;
		if (__div_wen)
			div_o <= div_wdata;
	end
end

endmodule
