/*******************************************************************************
*                          AUTOGENERATED BY REGBLOCK                           *
*                            Do not edit manually.                             *
*          Edit the source file (or regblock utility) and regenerate.          *
*******************************************************************************/

#ifndef _SDADC_REGS_H_
#define _SDADC_REGS_H_

// Block name           : sdadc
// Bus type             : apb
// Bus data width       : 32
// Bus address width    : 16

#define SDADC_CSR_OFFS 0
#define SDADC_DIV_OFFS 4
#define SDADC_DATA_OFFS 8

/*******************************************************************************
*                                     CSR                                      *
*******************************************************************************/

// Control and status register

// Field: CSR_ADC_AVA  Access: RW
// Set the avarage count of adc data.
#define SDADC_CSR_ADC_AVA_LSB  6
#define SDADC_CSR_ADC_AVA_BITS 3
#define SDADC_CSR_ADC_AVA_MASK 0x1c0
// Field: CSR_RST_FIFO  Access: RWF
// Write 1 to reset data fifo.
#define SDADC_CSR_RST_FIFO_LSB  5
#define SDADC_CSR_RST_FIFO_BITS 1
#define SDADC_CSR_RST_FIFO_MASK 0x20
// Field: CSR_FIFO_FULL  Access: ROV
// If 1, the received data fifo is full
#define SDADC_CSR_FIFO_FULL_LSB  4
#define SDADC_CSR_FIFO_FULL_BITS 1
#define SDADC_CSR_FIFO_FULL_MASK 0x10
// Field: CSR_FIFO_EMPTY  Access: ROV
// If 1, the received data fifo is empty
#define SDADC_CSR_FIFO_EMPTY_LSB  3
#define SDADC_CSR_FIFO_EMPTY_BITS 1
#define SDADC_CSR_FIFO_EMPTY_MASK 0x8
// Field: CSR_INT_PEND  Access: RWF
// If 0, SCLK low when idle. If 1, high when idle.
#define SDADC_CSR_INT_PEND_LSB  2
#define SDADC_CSR_INT_PEND_BITS 1
#define SDADC_CSR_INT_PEND_MASK 0x4
// Field: CSR_INT_EN  Access: RW
// If 1, interrupt signal when convert completed.
#define SDADC_CSR_INT_EN_LSB  1
#define SDADC_CSR_INT_EN_BITS 1
#define SDADC_CSR_INT_EN_MASK 0x2
// Field: CSR_ENABLE  Access: RW
// Write 1 to enable sdadc module
#define SDADC_CSR_ENABLE_LSB  0
#define SDADC_CSR_ENABLE_BITS 1
#define SDADC_CSR_ENABLE_MASK 0x1

/*******************************************************************************
*                                     DIV                                      *
*******************************************************************************/

// Clock divider register

// Field: DIV  Access: RW
#define SDADC_DIV_LSB  0
#define SDADC_DIV_BITS 8
#define SDADC_DIV_MASK 0xff

/*******************************************************************************
*                                     DATA                                     *
*******************************************************************************/

// ADC data FIFO

// Field: DATA  Access: RF
#define SDADC_DATA_LSB  0
#define SDADC_DATA_BITS 16
#define SDADC_DATA_MASK 0xffff

#endif // _SDADC_REGS_H_
