/*******************************************************************************
*                          AUTOGENERATED BY REGBLOCK                           *
*                            Do not edit manually.                             *
*          Edit the source file (or regblock utility) and regenerate.          *
*******************************************************************************/

// Block name           : timer
// Bus type             : apb
// Bus data width       : 32
// Bus address width    : 16

module timer_regs (
	input wire clk,
	input wire rst_n,
	
	// APB Port
	input wire apbs_psel,
	input wire apbs_penable,
	input wire apbs_pwrite,
	input wire [15:0] apbs_paddr,
	input wire [31:0] apbs_pwdata,
	output wire [31:0] apbs_prdata,
	output wire apbs_pready,
	output wire apbs_pslverr,
	
	// Register interfaces
	input wire  csr_en_i,
	output reg  csr_en_o,
	output reg csr_en_wen,
	output reg csr_en_ren,
	output reg  csr_int_en_o,
	output reg  csr_mode_o,
	output reg [15:0] csr_div_o,
	input wire  int_pending_pending_i,
	output reg  int_pending_pending_o,
	output reg int_pending_pending_wen,
	output reg int_pending_pending_ren,
	output reg [31:0] expire_count_count_o,
	input wire [31:0] current_count_count_i
);

// APB adapter
wire [31:0] wdata = apbs_pwdata;
reg [31:0] rdata;
wire wen = apbs_psel && apbs_penable && apbs_pwrite;
wire ren = apbs_psel && apbs_penable && !apbs_pwrite;
wire [15:0] addr = apbs_paddr & 16'hc;
assign apbs_prdata = rdata;
assign apbs_pready = 1'b1;
assign apbs_pslverr = 1'b0;

localparam ADDR_CSR = 0;
localparam ADDR_INT_PENDING = 4;
localparam ADDR_EXPIRE_COUNT = 8;
localparam ADDR_CURRENT_COUNT = 12;

wire __csr_wen = wen && addr == ADDR_CSR;
wire __csr_ren = ren && addr == ADDR_CSR;
wire __int_pending_wen = wen && addr == ADDR_INT_PENDING;
wire __int_pending_ren = ren && addr == ADDR_INT_PENDING;
wire __expire_count_wen = wen && addr == ADDR_EXPIRE_COUNT;
wire __expire_count_ren = ren && addr == ADDR_EXPIRE_COUNT;
wire __current_count_wen = wen && addr == ADDR_CURRENT_COUNT;
wire __current_count_ren = ren && addr == ADDR_CURRENT_COUNT;

wire  csr_en_wdata = wdata[0];
wire  csr_en_rdata;
wire  csr_int_en_wdata = wdata[1];
wire  csr_int_en_rdata;
wire  csr_mode_wdata = wdata[2];
wire  csr_mode_rdata;
wire [15:0] csr_div_wdata = wdata[31:16];
wire [15:0] csr_div_rdata;
wire [31:0] __csr_rdata = {csr_div_rdata, 13'h0, csr_mode_rdata, csr_int_en_rdata, csr_en_rdata};
assign csr_en_rdata = csr_en_i;
assign csr_int_en_rdata = csr_int_en_o;
assign csr_mode_rdata = csr_mode_o;
assign csr_div_rdata = csr_div_o;

wire  int_pending_pending_wdata = wdata[0];
wire  int_pending_pending_rdata;
wire [31:0] __int_pending_rdata = {31'h0, int_pending_pending_rdata};
assign int_pending_pending_rdata = int_pending_pending_i;

wire [31:0] expire_count_count_wdata = wdata[31:0];
wire [31:0] expire_count_count_rdata;
wire [31:0] __expire_count_rdata = {expire_count_count_rdata};
assign expire_count_count_rdata = expire_count_count_o;

wire [31:0] current_count_count_wdata = wdata[31:0];
wire [31:0] current_count_count_rdata;
wire [31:0] __current_count_rdata = {current_count_count_rdata};
assign current_count_count_rdata = current_count_count_i;

always @ (*) begin
	case (addr)
		ADDR_CSR: rdata = __csr_rdata;
		ADDR_INT_PENDING: rdata = __int_pending_rdata;
		ADDR_EXPIRE_COUNT: rdata = __expire_count_rdata;
		ADDR_CURRENT_COUNT: rdata = __current_count_rdata;
		default: rdata = 32'h0;
	endcase
	csr_en_wen = __csr_wen;
	csr_en_o = csr_en_wdata;
	csr_en_ren = __csr_ren;
	int_pending_pending_wen = __int_pending_wen;
	int_pending_pending_o = int_pending_pending_wdata;
	int_pending_pending_ren = __int_pending_ren;
end

always @ (posedge clk or negedge rst_n) begin
	if (!rst_n) begin
		csr_int_en_o <= 1'h0;
		csr_mode_o <= 1'h0;
		csr_div_o <= 16'h1;
		expire_count_count_o <= 32'h0;
	end else begin
		if (__csr_wen)
			csr_int_en_o <= csr_int_en_wdata;
		if (__csr_wen)
			csr_mode_o <= csr_mode_wdata;
		if (__csr_wen)
			csr_div_o <= csr_div_wdata;
		if (__expire_count_wen)
			expire_count_count_o <= expire_count_count_wdata;
	end
end

endmodule
