/*******************************************************************************
*                          AUTOGENERATED BY REGBLOCK                           *
*                            Do not edit manually.                             *
*          Edit the source file (or regblock utility) and regenerate.          *
*******************************************************************************/

#ifndef _TIMER_REGS_H_
#define _TIMER_REGS_H_

// Block name           : timer
// Bus type             : apb
// Bus data width       : 32
// Bus address width    : 16

#define TIMER_CSR_OFFS 0
#define TIMER_INT_PENDING_OFFS 4
#define TIMER_EXPIRE_COUNT_OFFS 8
#define TIMER_CURRENT_COUNT_OFFS 12

/*******************************************************************************
*                                     CSR                                      *
*******************************************************************************/

// Control and status register

// Field: CSR_EN  Access: RWF
// timer runs when en is high.
#define TIMER_CSR_EN_LSB  0
#define TIMER_CSR_EN_BITS 1
#define TIMER_CSR_EN_MASK 0x1
// Field: CSR_INT_EN  Access: RW
// generate irq signal when timer expired.
#define TIMER_CSR_INT_EN_LSB  1
#define TIMER_CSR_INT_EN_BITS 1
#define TIMER_CSR_INT_EN_MASK 0x2
// Field: CSR_MODE  Access: RW
// 0: one shot, 1: auto reload
#define TIMER_CSR_MODE_LSB  2
#define TIMER_CSR_MODE_BITS 1
#define TIMER_CSR_MODE_MASK 0x4
// Field: CSR_DIV  Access: RW
// timer clk = module clock / div
#define TIMER_CSR_DIV_LSB  16
#define TIMER_CSR_DIV_BITS 16
#define TIMER_CSR_DIV_MASK 0xffff0000

/*******************************************************************************
*                                 INT_PENDING                                  *
*******************************************************************************/

// timer interrupt pending register

// Field: INT_PENDING_PENDING  Access: RWF
// irq pending, write 1 to clear.
#define TIMER_INT_PENDING_PENDING_LSB  0
#define TIMER_INT_PENDING_PENDING_BITS 1
#define TIMER_INT_PENDING_PENDING_MASK 0x1

/*******************************************************************************
*                                 EXPIRE_COUNT                                 *
*******************************************************************************/

// timer expire count register

// Field: EXPIRE_COUNT_COUNT  Access: RW
// when timer counter == expire_count - 1, mean it expired.
#define TIMER_EXPIRE_COUNT_COUNT_LSB  0
#define TIMER_EXPIRE_COUNT_COUNT_BITS 32
#define TIMER_EXPIRE_COUNT_COUNT_MASK 0xffffffff

/*******************************************************************************
*                                CURRENT_COUNT                                 *
*******************************************************************************/

// timer current count register

// Field: CURRENT_COUNT_COUNT  Access: ROV
// timer current counter.
#define TIMER_CURRENT_COUNT_COUNT_LSB  0
#define TIMER_CURRENT_COUNT_COUNT_BITS 32
#define TIMER_CURRENT_COUNT_COUNT_MASK 0xffffffff

#endif // _TIMER_REGS_H_
